### ISSUE TITLE
Upgrade keycloak to 3.2.0

### ISSUE THREAD

**Issue by sbose78** [fabric8-services/fabric8-auth#1]
https://github.com/fabric8io/keycloak-deployment/pull/34

**Comment by sbose78** [comment]
@hectorj2f , let's put out the plan here when we come up with one :)

**Comment by hectorj2f** [comment]
Initially we'll use an empty postgresql database inside of our keycloak project in Openshift. 

The plan is:
1 - [x] Setup an environment similar to the one in production (`keycloak 3.2.0-CR1-SNAPSHOT`). This is done in our `keycloak-cluster-test` cluster in `rh-idev`.
2 - [ ] Verify which columns/table has been changed or dropped to repair. Also we need to check the mentioned migration scripts.
3 - [ ] Run an upgrade action in our test cluster to the latest version `3.2.0.Final`
4 - [ ] Check that things work as expected, regarding common KC operations

Other tests:
1 - [ ] Test the migration towards a clustered version
2 - [ ] Test core against this keycloak instance, or simply to run our new image against a local setup with the old one (we could use f8-platform) for that purpose.
3 - [ ] Load a backup of prod-preview kc data into another kc DB instance to validate the migration with "real" data.

**Comment by alexeykazakov** [comment]
Done. Closing.
