### ISSUE TITLE
Add API to get stored OpenShift/Github token.

### ISSUE THREAD

**Issue by sbose78** [fabric8-services/fabric8-auth#133]
## Get stored token by scope & resource
```
GET /api/token?for=<resource>&scope=<scope>
Authorization: Bearer <access_token>
```
**`<resource>`** - Resource we need token for. For example https://github.com/somecoolrepo or https://console.starter-us-east-2.openshift.com/console/project/coolproject

**`<scope>`** - required scope. Multiple scopes can be specified by separating them with a space. If not defined then the default scope is used. In the first version we support the default scopes only. Therefore, this parameter is optional.

**Example:**
`GET /api/token?for=https://github.com/somecoolrepo`

If there is no token with requested scopes for that user then a 401 response will be returned. That 401 response will contain **“WWW-Authenticate”** header in the following format:

`WWW-Authenticate: Link url=<link_url>, description=”<description>”`

**`<link_url>`** - URL to be used to link the user’s account to the required token provider. Optional.
**`<description>`** - Message which explains what happened. Optional.

**Example:**
`WWW-Authenticate: Link url=https://auth.openshift.io/api/token/link, description=”GitHub token is missing. Link GitHub account”
`

**Comment by alexeykazakov** [comment]
I've updated description
