### ISSUE TITLE
Add API to Link accounts.

### ISSUE THREAD

**Issue by sbose78** [fabric8-services/fabric8-auth#134]
## Linking Accounts

```
POST /api/token/link
Content-Type: application/x-www-form-urlencoded
Payload: for=<resource>&token=<access_token>&scope=<scope>&redirect=<redirect_url>
```

**`<resource>`** - Resource we need to link accounts for. For example https://github.com/somecoolrepo or https://console.starter-us-east-2.openshift.com/console/project/coolproject
**`<scope>`** - required scope. Multiple scopes can be specified by separating them with a space. Optional. If not defined then the default scope is used. Not supported in the first version!
**`<redirect>`** - after successful linking the client will be redirected to this URL. If not specified then the URL from the “Referer” header will be used. If both “Referer” header and “redirect” param are missing then a Bar Request response will be returned.
**`<access_token>`** - user’s access token

If the token for such user already exists then the account will be re-linked and the token will be updated.
In the first version, we support only **github** and **openshift** represents OSO-us-starter-2. Later an individual **openshift** provider will be associated with the user during signup by the registration app, as part of multicluster support.

**Example:**
```
POST /api/token/link
Content-Type: application/x-www-form-urlencoded
for=https://github.com/somecoolrepo&token=ABSDEF12345678990&redirect=https%3A%2F%2Fopenshift.io&scope=user%20public_repo
```

## Re-linking Accounts

If some services catches 401 when trying to use Git or OS token this service should return 401 to UI with the following header:

`WWW-Authenticate: Link url=<link_url_optional>, description=”<description_optional>”`

UI should initiate re-linking when catches such 401 response.

**Comment by alexeykazakov** [comment]
I've updated the issue description.
