### ISSUE TITLE
It should be possible to run both wit and auth services locally on the same host for development and testing 

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8-services/fabric8-auth#14]
This is a follow up on https://github.com/fabric8-services/fabric8-auth/pull/11 which was a temporal workaround to fix our CI.

@sbose78 please work with @hectorj2f to fix our docker-test-integration.

So, we will probably need to revert https://github.com/fabric8-services/fabric8-auth/pull/11 and properly fix the test integration docker container (my attempt https://github.com/fabric8-services/fabric8-auth/pull/12/ didn't help).

**Comment by alexeykazakov** [comment]
@hectorj2f if I apply https://github.com/fabric8-services/fabric8-auth/pull/12/files then the DB is available via 0.0.0.0:5433 but not via 172.17.0.3:5433.
But even if I set AUTH_POSTGRES_HOST to 0.0.0.0 from 172.17.0.3 then 0.0.0.0:5433 is still unavailable from the auth container. But I can connect to the DB from my host (0.0.0.0:5433).

**Comment by hectorj2f** [comment]
@alexeykazakov I'll push a quick PR with the fix, it is an easy one.

**Comment by alexeykazakov** [comment]
Oh, thanks @hectorj2f I was hopping for your docker expertise ;)

**Comment by alexeykazakov** [comment]
Fixed.
