### ISSUE TITLE
Persist Keycloak Infinispan session cache in DB?

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8-services/fabric8-auth#146]
We should consider switching infinispan from in-memory only to a data grid mode for persisting sessions in a DB.

Related to https://github.com/fabric8-services/fabric8-auth/issues/95

**Comment by sbose78** [comment]
Agreed.
Will save us from a lot of weird errors with just-created-tokens.

**Comment by sbose78** [comment]
Don't think we should invest effort on this anymore :)
