### ISSUE TITLE
Changes needed in various apps for changes in github token url 

### ISSUE THREAD

**Issue by sbose78** [fabric8-services/fabric8-auth#149]
What previously used to be 

```
https://sso.openshift.io/auth/realms/fabric8/broker/github/token
Authorization: Bearer <access_token>
```

Will now be: 
```
GET https://auth.openshift.io/api/token?for=https://github.com
Authorization: Bearer <access_token>
```

Please note:
You can optionally pass the `Accept: application/x-www-form-urlencoded` to get it in a url encoded format. The default is `application/json` . 

This thread will be used to track the places in our system where this change will cause an impact.

Part of https://github.com/fabric8-services/fabric8-auth/issues/21

List of services:

- [x] che-starter https://github.com/redhat-developer/che-starter/issues/229
- [x] che / rh-che assembly / tenant https://github.com/redhat-developer/rh-che/issues/379
- [x] app wizard / forge https://github.com/fabric8io/fabric8-generator/issues/70
- [x] Codebases page in UI & getting_started page in UI https://github.com/fabric8-ui/fabric8-ui/pull/2011

**Comment by ibuziuk** [comment]
@sbose78 WDYT about having a checkbox list with all the apps that need to do a migration in this issue (e.g. che-starter / che-server etc.) ? IMO it would be easier to track all the osio pieces that need to do a migration

**Comment by alexeykazakov** [comment]
@ibuziuk +1. That was the plan actually. To have such a list of all places/apps.

**Comment by ibuziuk** [comment]
@alexeykazakov cool, I have added che-starter ;-)

**Comment by sbose78** [comment]
Thanks @ibuziuk , yeah that's exactly what I was looking for :)
