### ISSUE TITLE
Service Accounts

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8-services/fabric8-auth#150]
We need REST API for which can be used by services to "login" and obtain service account tokens which can be used to authenticate services.

**Comment by fche** [comment]
There is also a lesser need: no service account tokens, just the list of tenants / namespaces in each of their clusters.

**Comment by alexeykazakov** [comment]
@fche we would need to protect that API which will give you the list of tenants/namespaces. This issue is for service accounts which could be used to bring some AuthZ to that API.

**Comment by alexeykazakov** [comment]
Replaced by https://github.com/fabric8-services/fabric8-auth/issues/72
