### ISSUE TITLE
User should be able to remove and re-connect GitHub/OSO accounts in user's profile page

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8-services/fabric8-auth#151]
While we still have to support linking and re-linking GitHub/OSO on demand (whatever service needs some linking/re-linking it should return www-authenticate header - https://github.com/fabric8-services/fabric8-auth/issues/38) it also would be pretty useful to add GitHub/OSO account management functionality to user's profile page.
On this page, user should be able to:
- connect accounts if not connected yet.
- re-connect accounts if already connected.
- re-move accounts if already connected.

**Comment by alexeykazakov** [comment]
Related to https://github.com/openshiftio/openshift.io/issues/390

**Comment by alexeykazakov** [comment]
@catrobson does it make sense to you?

**Comment by catrobson** [comment]
@alexeykazakov - yes, we already have designed this into a future version of the Profile page that we've been building out.  @mindreeper2420 - can you link this up with our profile and settings stories?  Also would be good to know if this means we could actually take action on the profile page 
 (link new account, remove account, etc) vs. having the more static information we have designed in so far.

**Comment by alexeykazakov** [comment]
@catrobson re-linking accounts is already available. And we are working on REST API for removing accounts - https://github.com/fabric8-services/fabric8-auth/issues/138
Should be ready this week.

**Comment by mindreeper2420** [comment]
@catrobson @alexeykazakov Here is the current UX story: https://github.com/fabric8-ui/fabric8-ux/issues/715. I've completed a good amount of it, but still determining what is available vs what we need to request for accessing various bits of information.

**Comment by alexeykazakov** [comment]
Done.
