### ISSUE TITLE
Allow service accounts to be configured

### ISSUE THREAD

**Issue by sbryzak** [fabric8-services/fabric8-auth#153]
For the purpose of authenticating the resource servers (such as Work Item Tracker) that consume fabric8-auth services, it is necessary to be able to configure service accounts for these.

A new configuration file, **fabric8-auth-service-account-secrets.conf** will be used to configure the service accounts.  An entry in this file may look like this:

```
{
    "accounts": [
        {
            "name":"Work Item Tracker",
            "id":"wit-userid",
            "credentials":"0123456789abcdef"
        }
    ]
}
```

By default, fabric8-auth will look for this file in the **/etc/fabric8/** folder, failing to find it there it will search for it in the running directory, followed by the **/conf** directory (relative to the running dir), and finally failing that in the **../conf** directory.

The location of the configuration file may be overridden by an environment parameter, or a command line parameter.

This is a sub-issue of #72

**Comment by alexeykazakov** [comment]
@sbryzak I think we should be able to configure a pair of credentials for each account, so, we could rotate them:
```

{
    "accounts": [
        {
            "name":"Work Item Tracker",
            "id":"wit-userid",
            "credentials": ["0123456789abcdef", "sdfhsldfjdfjlj"]
        }
    ]
}
```
1. AuthZ service checks all available credentials during SA "login".
2. When we need to update credentials we just add a new one to the array.
3. Update the credentials in the client service.
4. Remove the old credentials from the AuthZ service.

So, we have changed the credentials without any downtime. WDYT?

**Comment by alexeykazakov** [comment]
I also renamed credentials to secrets ^^^
