### ISSUE TITLE
Call WIT after generating test tokens in Auth

### ISSUE THREAD

**Issue by sbose78** [fabric8-services/fabric8-auth#161]
Everytime we do a `/api/token/generate` https://github.com/fabric8-services/fabric8-auth/blob/master/controller/token.go#L127
we persist user/identities in the database.

To ensure that WIT can re-use the tokens, we need the user/identities created on the WIT side too.
We currently do this everything there is a new user login in interactively using Auth- https://github.com/fabric8-services/fabric8-auth/blob/master/login/service.go#L211

You need to call `remoteWITService.CreateWITUser(..)`   as show above while generating the test tokens.

**Comment by kishansagathiya** [comment]
@sbose78 let me be sure about this, 
What we want is that on running `./bin/auth-cli generate token -H localhost:8089 --pp`, we want to check wit's database and if user and identities are not there, populate them.
Is that right?

**Comment by sbose78** [comment]
This is correct @kishansagathiya . 
Note: You wouldn't be able to talk to WIT"s db directly - you would have to talk over the wire , ie, the WIT service.

**Comment by alexeykazakov** [comment]
We don't need to check if it exists in WIT or not. If the identity is created in Auth then create it in WIT. If it's updated then update it in WIT.

**Comment by sbose78** [comment]
yeah so in this case, just do a `createWITUser(..)` when the test tokens are generated in auth. No need to check if exists - if it does, we could silently fail. Our objective is to ensure that WIT has the users.

> If it's updated then update it in WIT.

This would anyway be taken care of in the User API, so nothing to be done here.
