### ISSUE TITLE
Support Oauth2 flow for user login

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8-services/fabric8-auth#196]
This is about supporting `grant_type=authorization_code` for users login flow.

For user login, here are the steps:
1. Client sends a generated state. Auth "proxies" it to KC and thereby initiates the first in oauth2
2. KC redirects to IdP etc. User logs in..
3. KC `calls back` Auth with a `code`
4. Auth passes the `code` to Client ( UI or another services )
5. Client then calls KC to do the `code` <-> `token` exchange.
Auth works as a smart proxy here between client and KC.

Part of https://github.com/fabric8-services/fabric8-auth/issues/145

**Comment by kishansagathiya** [comment]
@sbose78 @alexeykazakov 
I am thinking a flow as follows
- To get authorization_code. We need to create /api/login/authorize endpoint
``` 
GET /api/login/authorize
        response_type=code&
        client_id=SERVICE_ACCOUNT_ID&
        redirect_uri=CALLBACK_URL&
        scope=read
```

- To get the access token
```
POST /api/token
    grant_type=authorization_code&
    client_id=SERVICE_ACCOUNT_ID&
    client_secret=SERVICE_ACCOUNT_SECRET&
    code=AUTHORIZATION_CODE&
    redirect_uri=CALLBACK_URL
```

**Comment by alexeykazakov** [comment]
Looks good. But I think we can support public clients only for now. It doesn’t make much sense to use client secrets in UI.

**Comment by sbose78** [comment]
There should be approx two APIs on the Auth side to make Auth act like a soft proxy : 

> Client sends a generated state. Auth "proxies" it to KC and thereby initiates the first in oauth2
This should be API 1 .
Auth needs to accept the `state` here from the UI ( or any other client ).

> KC redirects to IdP etc. User logs in..
> KC calls back Auth with a code
this should be API 2, which will be called (back) by KC.

> Auth passes the code to Client ( UI or another services )
> Client then calls KC to do the code <-> token exchange.
> Auth works as a smart proxy here between client and KC.

Are we on the same page @alexeykazakov , @kishansagathiya  ? :)

**Comment by alexeykazakov** [comment]
If by API 1/2 you mean endpoint 1/2 then yes.

**Comment by sbose78** [comment]
Right, endpoint. Thanks.

**Comment by kishansagathiya** [comment]
@sbose78 @alexeykazakov 
I was able to implement the authorize api to some extent ( for the most parts it's a copy of login api), but I need your opinion on this. I would be able to finish it after that.
Since internally there is a login happening in /api/authorize, what should be the value of parameters which are supposed to be passed to login action i.e, link and api_client or should I pass them to authorize as parameters?

**Comment by alexeykazakov** [comment]
We don't need to support link. But let's support api_client parameter.
