### ISSUE TITLE
UI - Enable updates to accept empty strings for User's profile for optional fields

### ISSUE THREAD

**Issue by kishansagathiya** [fabric8-services/fabric8-auth#198]
The API has been modified to enable updates to accept empty strings for User's profile for optional fields https://github.com/fabric8-services/fabric8-auth/pull/189, but the UI still send the previous value to the api if these fields are empty

**Comment by rohitkrai03** [comment]
@alexeykazakov This was handled by https://github.com/fabric8-ui/fabric8-ui/pull/2978
