### ISSUE TITLE
Migrate from WIT to Auth

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8-services/fabric8-auth#20]
- [ ] Start calling Auth from WIT when users are logged in or updated. So, we update all users/identities in Auth if related changes are made in WIT. We also should stop creating/deleting Keycloak resources when a space is created/deleted in WIT. We should call Auth (from WIT) to create/delete resources instead. WIT is still an entry point for all user/identity/login/etc request.
- [ ] Copy all existing users/identities/space resources from WIT DB to Auth DB
- [ ] Stop using WIT for login, user updates, etc and switch all clients (UI) to Auth for that. Auth becomes our entry point for all these requests instead of WIT. Start updating user/identity in WIT when relevant changes are made in Auth.
- [ ] Refactor the WIT user/identity model to keep only minimum user/identity information relevant to WIT.

**Comment by sbose78** [comment]
Looks good, will create sub-tasks and assign them.

**Comment by sbose78** [comment]
The relevant tasks in correct order is this : 

1. Copy over all user/identity information from WIT DB to AUTH DB 
2. Redirect login requests from WIT to AUTH , + support Auto sync of identity/user info from AUTH to WIT.
3. Redirect user profile updates' information from WIT to AUTH
4. Redirect space resource creation from WIT to AUTH

**Comment by alexeykazakov** [comment]
#26 We can't just redirect requests from WIT to Auth and support Auto sync by calling WIT from Auth. We will get an infinite loop of calls between WIT and Auth.
We should copy the existing users/idenities and space resources only when the auto sync is in place. Otherwise we can lose some data if something changed between coping and auto sync.

**Comment by alexeykazakov** [comment]
Closing in favor of https://github.com/fabric8-services/fabric8-auth/issues/65 (Migrate space authorization)
We also need to create an issue to cover User management migration.
