### ISSUE TITLE
OSO token retrieval doesnt work in prod-preview

### ISSUE THREAD

**Issue by sbose78** [fabric8-services/fabric8-auth#200]
`GET /api/token` api , the OSO token retrieval is not working.

`Bad value for parameter 'for': 'https://api.free-int.openshift.com' (expected: 'URL to a github.com or openshift.com resource`  
Found this issue a while back and @vpavlin confirmed it.

However, the `GET /api/user` response  returns the correct `https://api.free-int.openshift.com`
and the env var is set fine too.

I tried passing the starter OSO url ( `...starter-us-east-2.openshift.com` ) , and that returned me a token - which is stranger.

**Comment by sbose78** [comment]
I figured out why this is happening - 
https://github.com/fabric8-services/fabric8-auth/blob/master/token/link/link.go#L262

```
	if resourceURL.Host == "github.com" {
		return NewGitHubConfig(service.config.GetGitHubClientID(), service.config.GetGitHubClientSecret(), service.config.GetGitHubClientDefaultScopes(), authURL), nil
	} else {
		clusters := service.config.GetOSOClusters()
		for apiURL, cluster := range clusters {
			if strings.HasPrefix(forResource, apiURL) {
				return NewOpenShiftConfig(cluster, authURL)
			}
		}
	}
```
`clusters := service.config.GetOSOClusters()`

This doesn't read the cluster info from `AUTH_OSO_CLIENT_APIURL` which for prod-preview is api.free-int....

**Comment by alexeykazakov** [comment]
/etc/fabric8/oso-clusters.conf is not mounted in preview. This is the reason of this problem.

**Comment by alexeykazakov** [comment]
It's fixed now.
