### ISSUE TITLE
possible fd leak in unclosed connection to f8tenant

### ISSUE THREAD

**Issue by fche** [fabric8-services/fabric8-auth#204]
From pcp monitoring of fabric8/osio on both prod and devel clusters, the per-process open-fd-count metrics show a monotonic increase of open fds for the auth / tenant / core pods.  It appears that auth and core make http connections to tenant that stick around ... indefinitely?  Over the course of a few hours, several hundred fds stay around; high water observed has been in the thousands.

(Seeing the actual connections between the pod processes requires ss or lsof or some other such tool, which are not by default in the container images.)

**Comment by alexeykazakov** [comment]
Thanks for the report @fche! I hope I found all the places were we do not close the response properly - https://github.com/fabric8-services/fabric8-auth/pull/205
@xcoulon it's worth checking tenant and WIT services too.
