### ISSUE TITLE
Scenarios for performance testing

### ISSUE THREAD

**Issue by sbose78** [fabric8-services/fabric8-auth#209]
( This is a work-in-progress and being updated. However, the info provided here is accurate )

1. User login
`GET /api/login?redirect=https://auth.openshift.io/api/status`
This returns a redirect. 
The next steps need user interaction.

2. Get User info

```
GET /api/user
Authorization: Bearer <Token>
```
```
GET https://auth.openshift.io/api/users/3383826c-51e4-401b-9ccd-b898f7e2397d
```
( no auth )

```
GET https://auth.openshift.io/api/users?filter[username]=shbose
```
( no auth )

3. Create Space ( this currently has a keycloak interaction - but will go away soon )
< to be added >

4. Link accounts ( Github & OpenShift Online )

```
POST /api/token/link
for=https://github.com/alexeykazakov-osio/somecoolrepo&
redirect=https://auth.openshift.io/api/status&
token=<USER_ACCESS_TOKEN>
```
This needs to be a 'form post' something like https://github.com/alexeykazakov/linker/blob/master/static/link.html
This, as you could guess would cause a redirect to github/OpenShiftOnline.

5. Get tokens for linked accounts ( Github & OpenShift Online )

```
GET /api/token?for=https://api.starter-us-east-2.openshift.com
Authorization: Bearer <Token>
```
```
GET /api/token?for=https://github.com
Authorization: Bearer <Token>
```

6. Refresh login token

```
POST /api/token/refresh
Authorization: Bearer <Token>
Content-Type: application/json 

{"refresh_token":"<Refresh Token>"}

```

**Comment by sbryzak** [comment]
Addressed as part of performance testing.
