### ISSUE TITLE
List of all services/parts of OSIO which uses Keycloak to get user's OSO tokens

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8-services/fabric8-auth#213]
This list would help us to see if we can easily switch entire OSIO to Auth to get the tokens while we are waiting for the OSO Proxy.
Please also mention all the services which use OSO tokens but don't use KC to get them.

**Comment by sbose78** [comment]
- pipelines/applications UI : calls API to get token at the *refresh* interval and then stores the token in local storage https://github.com/fabric8-ui/ngx-login-client/blob/master/src/app/auth/authentication.service.ts . This stored token in local storage is used to call Openshift API , the response from which is used to render the UI components.
- fabric8-tenant : https://github.com/fabric8-services/fabric8-tenant/blob/master/keycloak/openshift.go
- forge / fabric8-generator : https://github.com/fabric8io/fabric8-generator/blob/aa144841854032d316b5bdd9964d68aba19a8d7b/src/main/java/io/fabric8/forge/generator/keycloak/KeycloakClient.java#L38
- Che : Used by che host for validating access to spaces https://github.com/redhat-developer/rh-che/blob/d8655d61cd3831da2eec90ddd17b23a420bc6a05/dev-scripts/openshift_deploy.sh#L143
- tenant jenkins : No Impact. uses a service account https://github.com/fabric8-services/fabric8-tenant-team/blob/master/packages/fabric8-tenant-team/src/main/fabric8/stage-jenkins-edit-rb.yml
- analytics : No impact

**Comment by gastaldi** [comment]
@sbose78 the Forge link is: https://github.com/fabric8-launcher/launcher-backend/blob/6e1a979151b0328e1e03573cb2d631bbe8b309fd/addons/osio-addon/src/main/java/io/fabric8/forge/generator/keycloak/KeycloakEndpoint.java#L29

That repository is no longer maintained after the codebase merge

**Comment by sbose78** [comment]
Thanks @gastaldi .
