### ISSUE TITLE
Implement read resource endpoint

### ISSUE THREAD

**Issue by sbryzak** [fabric8-services/fabric8-auth#223]
From the design document:

This method returns the details of the resource with the specified resource identifier:

```
GET /api/resource/KX3A-39WE HTTP/1.1
Authorization: Bearer MHg3OUZEQkZBMjcx
```

A successful response is indicated by a 200 OK header, and returns the details of the resource as a JSON document in the body.  The child_resource_ids parameter is a custom property (not part of the UMA specification) that lists the identifiers of resources that are child resources of the specified resource.

```
HTTP/1.1 200 OK
Content-Type: application/json
...
{  
   "_id":"KX3A-39WE",
   "resource_scopes":[  
      "read-public",
      "post-updates",
      "read-private",
      "http://www.example.com/scopes/all"
   ],
   "child_resource_ids":[
      "JK31-4927”
    ]
   "icon_uri":"http://www.example.com/icons/sharesocial.png",
   "name":"Tweedl Social Service",
   "type":"http://www.example.com/rsrcs/socialstream/140-compatible"
   "parent_resource_id":"KX30-1234"
}
```

**Comment by alexeykazakov** [comment]
What if the list of child resources is too big? Shouldn't we move this list to GET /api/resource/KX3A-39WE/children and provide pagination there?

**Comment by sbryzak** [comment]
We need to define a list of the resource type strings in order to include them in the migration script.  I'm thinking that it makes sense to follow the example that the UMA spec provides and use a URI that represents  the resource endpoint, for example something like:

```
http://api.openshift.io/api/area
http://api.openshift.io/api/workitem
http://api.openshift.io/api/workitem/comment
```

Suggestions welcome.

**Comment by sbryzak** [comment]
For the record, this issue introduced the following resource type:

`openshift.io/resource/area`
