### ISSUE TITLE
Implement update resource endpoint

### ISSUE THREAD

**Issue by sbryzak** [fabric8-services/fabric8-auth#224]
This endpoint is used to update the details of an existing resource

Sample request/response from the design document:

```
PUT /api/resource/9UQU-DUWW HTTP/1.1
Content-Type: application/json
Authorization: Bearer 204c69636b6c69
...
{  
   "resource_scopes":[  
      "http://photoz.example.com/dev/scopes/view",
      "public-read"
   ],
   "description":"Collection of digital photographs",
   "icon_uri":"http://www.example.com/icons/sky.png",
   "name":"Photo Album",
   "type":"http://www.example.com/rsrcs/photoalbum"
   "parent_resource_id":"KX30-1234"
}
```

Successful response:

```
HTTP/1.1 200 OK
...
{  
   "_id":"9UQU-DUWW"
}
```

**Comment by alexeykazakov** [comment]
If I understand it right PUT should be used to replace the existing resource. PATCH looks better here if we want to support partial updates of the existing resource. Let's say you want to update the description only so you can send a PATCH with the description field in the payload only. WDYT?

**Comment by sbryzak** [comment]
I would say it depends on how the UI allows an update to be made.  If a form is presented to the user that allows a number of field values to be updated, and the update only occurs when they click an "Apply" button then the PUT request is the way to go.  If updates to fields are "live", i.e. they occur as a user makes a change to an individual field then the PATCH request would be more suitable.

**Comment by alexeykazakov** [comment]
PATCH is more flexible anyway, isn't it? If you support PATCH do you need to support PUT at all?

**Comment by sbryzak** [comment]
In the former use case I just described, If we only support PATCH then additional logic may be required by the client to determine which field values have changed.  If the client is going to update all fields _anyway_, then we might as well use the PUT request. The other option is that we support both, PUT in order to conform with UMA (should compatibility become more important in the future) and PATCH if the UI supports the updating of individual fields.

**Comment by sbryzak** [comment]
I think it's important to identify the actual use cases here, in the case of resource registration we need to ask the question _what is going to change_?  I cannot identify any use cases in which the resource_id, resource_type and description fields will change here, and in my opinion the owner_id will never change also (under what circumstances would a resource change owners?).  This leaves the parent_resource_id, which I think can feasibly be changed if resources are "rearranged/restructured" within their hierarchy, e,g, an area is moved to another area within a space.  

Based on these use cases, I'm inclined to think that a simple PATCH might be enough, however I also think that there is value in supporting PUT as well for compatibility sake, seeing as it won't be much of an additional effort to support both methods.

**Comment by alexeykazakov** [comment]
To be honest I'm very skeptical about any future compatibility with other UMA solutions. So, let's pick up best ideas but it's perfectly fine not to follow UMA spec if it doesn't make sense to us.

Regarding this particular case... ownership change could be interesting in the future. We could allow transferring space ownership similar to what GitHub supports when you need to move a repo or an org to another owner.

Anyway, +1 to PATCH and maybe add PUT too (but it's optional).
