### ISSUE TITLE
Init tenant when user is created by registration app

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8-services/fabric8-auth#226]
Currently we do it when GET /api/user is called. As soon as the registration app switches to our new API to create users we need to init tenant when user is created.

Depends on https://github.com/openshift/online-registration/issues/762
Part of https://github.com/fabric8-services/fabric8-auth/issues/162 and https://github.com/openshiftio/openshift.io/issues/948#issuecomment-351371024

**Comment by sbose78** [comment]
This is technically not feasible at the moment because the user wouldn't have a connected OSO account. 
In the recent future, we would be looking at a more lazy initialization option. Since we wouldn't have any worked planned on this in the recent future - I am closing this.
