### ISSUE TITLE
Return 409 Conflict if the user already exists when creating a new user

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8-services/fabric8-auth#230]
When registration app calls Auth to create already existing user we should return 409 Conflict

Related to https://github.com/fabric8-services/fabric8-auth/issues/162

**Comment by sbose78** [comment]
I guess it returns a 50X internal error now, but yeah 409 should be the correct way.

**Comment by tiwillia** [comment]
It would be helpful if the error message or payload included the user's ID, since the only way to get a user is by the user's ID or to list all users and select by ID.
