### ISSUE TITLE
Can't run test TestRunUserREST

### ISSUE THREAD

**Issue by kishansagathiya** [fabric8-services/fabric8-auth#232]
Can't run tests with this. 
```
AUTH_DEVELOPER_MODE_ENABLED=1 AUTH_RESOURCE_DATABASE=1 AUTH_RESOURCE_UNIT_TEST=0 go test ./controller/ -v -run TestRunUserREST
```

**Comment by kishansagathiya** [comment]
In show action of /user one of the responses in NotModified, in I don't see the code returning NotModified anywhere. Tests are also failing for similar reasons (because the response is not NotModified)

**Comment by sbose78** [comment]
@kishansagathiya could you open a PR with a fix please? would be a nice way to evaluate :)

**Comment by kishansagathiya** [comment]
@sbose78 It doesn't seem like we are returning 304 NotModified. I tried the api on my local a bunch of times and I got 200 OK all the time, even though I Etag and Last-Modified were same everytime. Yes, Let me open a PR as well.

**Comment by kishansagathiya** [comment]
Found the code for 304
