### ISSUE TITLE
api/authorize should not require state param to be UUID

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8-services/fabric8-auth#234]
Currently api/authorize requires state param to be UUID. We should not limit it to UUID. Please check the OAuth2 spec to see if there is any requirements to the state or it can be any string.

This is a follow up issue on https://github.com/fabric8-services/fabric8-auth/pull/210#issuecomment-352968458

**Comment by kishansagathiya** [comment]
OAuth2.0 doesnt require us to use state as UUID. We can remove this requirement. Also right now /api/authorize returns 307 Temporary Redirect on success, but as per the specs it should give 302 Found.
https://tools.ietf.org/html/rfc6749#section-4.1

**Comment by alexeykazakov** [comment]
From the spec:  `state      = 1*VSCHAR`
So, state can be any not empty string.

**Comment by sbose78** [comment]
302 might get a bit messy on the Angular side - as my experience with 30Xs while working on the account linking UI task:

 "You can't really "catch" a 302 redirect response. The browser catches it before Angular get it's hand on it. so actually, when you do receive your response - it is already too late."
https://stackoverflow.com/a/24785762/823386

So let's keep it as 307 for now :)

**Comment by alexeykazakov** [comment]
But I think it's OK if Angular doesn't catch 302 from /authorize and it's handled by browser? Or I'm missing something?

**Comment by sbose78** [comment]
With a 302, 
If on the UI side, we do a `window.location=` , then the redirect would be followed, if Ajax then it's a problem :)

**Comment by kishansagathiya** [comment]
I remember, state is UUID, because some functions expect it to be UUID (like this https://github.com/fabric8-services/fabric8-auth/blob/master/token/oauth/oauth2.go#L84:6) If we were to change that we will have to change such functions.

**Comment by alexeykazakov** [comment]
Yes, we need to refactor our state table. Add a new column STATE there.
