### ISSUE TITLE
Copy over all user/identity information from WIT DB to AUTH DB

### ISSUE THREAD

**Issue by sbose78** [fabric8-services/fabric8-auth#25]
Copy all the existing users/identities from WIT to Auth (so, all the users are in sync in both WIT and Auth)

Part of https://github.com/fabric8-services/fabric8-auth/issues/79

**Comment by alexeykazakov** [comment]
Auto sync should be in place by the time we copy the existing info.

**Comment by alexeykazakov** [comment]
@sbose78 I updated the issue description

**Comment by alexeykazakov** [comment]
Blocked by https://github.com/fabric8-services/fabric8-auth/issues/26

**Comment by alexeykazakov** [comment]
Done.
