### ISSUE TITLE
Update user in Keycloak based on Auth DB during login

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8-services/fabric8-auth#250]
When user is logging into OSIO we should:
1. Update Keycloak account if there is something out of sync with the Auth DB. Auth DB always wins (Name, Approved, Company, etc).
2. If updated then refresh token, so, all claims are updated too in the token.
3. Issue the updated token with all claims in sync with the Auth DB.

As soon as we implement the above flow ^ approving users in preview will be more tricky ;)

**Comment by sbose78** [comment]
Once this is implemented we would need to make an API call with a service account token to update `approved` attribute ;)

**Comment by alexeykazakov** [comment]
Yep. Was thinking about this too :) Approving users in preview will be a bit more tricky.

**Comment by sbose78** [comment]
In prod, users are approved by online-registration triggering the API Call.
in preview, a human would have to make the API call ( with a service account token ) ? :)

**Comment by alexeykazakov** [comment]
Correct.

**Comment by sbose78** [comment]
> Issue the updated token with all claims in sync with the Auth DB.

What if the user has changed something that we don't save in token claims? In that case there needn't be a refreshed token.

On a sidenote,
@alexeykazakov 
The token claims contains the following username info but does not have `cluster`, `bio` etc.
Should we add more attributes to the token claims from the user's profile ? The only one that could go in ( and be useful ) is `cluster`. What do you think ?
```
type TokenClaims struct {
	Name          string                `json:"name"`
	Username      string                `json:"preferred_username"`
	GivenName     string                `json:"given_name"`
	FamilyName    string                `json:"family_name"`
	Email         string                `json:"email"`
	Company       string                `json:"company"`
	Approved      bool                  `json:"approved"`
        ............
        ............
```

**Comment by alexeykazakov** [comment]
Cluster seems to be useful. But let’s not add new attributes to KC for now. I hope we will be able to start generating tokens in Auth soon (as soon as we switch Che to Auth and start using Auth for OSO token management).

And yes, we need to refresh token only if something is changed in claims.
