### ISSUE TITLE
Delegate userProfile+login requests from WIT to AUTH

### ISSUE THREAD

**Issue by sbose78** [fabric8-services/fabric8-auth#26]
**Login**:
Delegate actual login to Auth when WIT login is called. WIT will need to keep creating users/identities in the WIT DB when login is called.

**User profile updates**:
Call the corresponding Auth API to update users/identities when the user/identity is updated in WIT. If user doesn't exist in Auth then Auth should just ignore such a request (it may happen if it's an old user created before migration).

WIT should pass a special parameter with all Auth requests to let Auth know that these requests are cumming from WIT (we will need it later when we switch UI to Auth and start notifying WIT about new/updated users to avoid an endless loop).

Part of https://github.com/fabric8-services/fabric8-auth/issues/79

**Comment by alexeykazakov** [comment]
We should be careful here not to provide an infinite loop. We can't just redirect (via http redirect) to Auth when UI calls WIT let's say to update a user and then call the same WIT endpoint from Auth to sync the data. It will redirect to Auth again.

**Comment by sbose78** [comment]
Correct, I implied 'delegate'.

**Comment by alexeykazakov** [comment]
@sbose78 I updated the issue description
