### ISSUE TITLE
Show if email is verified in UI

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8-services/fabric8-auth#262]
Current workflow:
1. User edits email in the profile page
2. We send a verification email
3. User clicks on the link in th email
4. We mark the email verified in our backend and forward user to openshift.io/_home

What we should add on top of this:
1. Show if email is verified or not on user profile page
2. Add "verify" action for unverified emails
3. When user clicks on the verification link in the verification email we should redirect to OSIO UI when user can see that the verification was successful or failed.

See also https://github.com/fabric8-ui/fabric8-ux/issues/920

**Comment by sbose78** [comment]
> When user clicks on the verification link in the verification email we should show a pop up (?) notification in the browser with success or failure message.

( as per UX ) 
On clicking verification link, user would be redirected to https://redhat.invisionapp.com/share/U2F2YVAT5#/screens/270598823

Are you OK with this?

**Comment by alexeykazakov** [comment]
> Are you OK with this?

Yes. Let me correct the description. It doesn't matter if it's a pop up notification or a dedicated page. We just have to let user know that the verification was successful. Or not :)

**Comment by sbose78** [comment]
https://github.com/fabric8-ui/fabric8-ui/pull/2538/files 

is the fix/work for this https://github.com/fabric8-ui/fabric8-ui/pull/2538/files , right ?

**Comment by alexeykazakov** [comment]
https://github.com/fabric8-ui/fabric8-ui/pull/2538 is only about the page we show after the user clicks on the verification link in the email. Unless I missed something:
> 3. When user clicks on the verification link in the verification email we should redirect to OSIO UI when user can see that the verification was successful or failed.

So, it's only the step 3 from the desired flow above.
We still need to implement the steps 1 and 2 too: 
> 1. Show if email is verified or not on user profile page
> 2. Add "verify" action for unverified emails

**Comment by sbose78** [comment]
That is correct, @alexeykazakov .

**Comment by rohitkrai03** [comment]
@alexeykazakov  Are there any wireframes from UX team available for step 1 and step 2 you mentioned?

**Comment by alexeykazakov** [comment]
@rohitkrai03 not yet. You can create an issue for the UX team here - https://github.com/fabric8-ui/fabric8-ux

**Comment by rohitkrai03** [comment]
@sbose78 @alexeykazakov What will happen if user is not verified and he clicks on the verify button?

**Comment by alexeykazakov** [comment]
@rohitkrai03 oh right. We actually don’t have dedicated API for email verification initiation :)
Currently we initiate email verification (we send a email with a link) when email is updated. We need to add a new endpoint which we can call from UI explicitly.

**Comment by sbose78** [comment]
Will add the API today https://github.com/fabric8-services/fabric8-auth/issues/369

**Comment by catrobson** [comment]
The updated user profile with editing the e-mail can be found here.  Clicking to save the new e-mail should validate the e-mail - I don't believe an extra button is needed to add confusion about this for the users.

https://redhat.invisionapp.com/share/E9FH915D3U7

**Comment by alexeykazakov** [comment]
@catrobson 
1. User updates email in the user profile
2. OSIO sends a link to verify email
3. User loses the link/emai

What is the user supposed to do now? We could block UI for this user until he/she verifies email but then we need to redirect user to a new page where the user can 1) re-send verification email 2) update email again in case the email was updated by mistake to something incorrect. 3) we will need to check email verification in UI to redirect to that page, etc. This is just harder to implement.

Another example is GitHub. There is just a label for an verified email + a button to re-send verification email.

**Comment by catrobson** [comment]
So to make sure I'm understanding, the user has full access to the system even if their e-mail is unverified so they can get to this page?  Then verifying the e-mail only is making sure we can send them information there like notifications, and it is separate from the authentication system for the application?

I think you're saying this is the flow:

1. I'm already a user of OSIO, logged in.
2. I go to my profile, and change my e-mail.  **this has no impact on my username/password used to access OSIO**
3. I get an e-mail (or I don't), and click verify.  We verify and they go happily on their way.
3b.  They lose the e-mail.  They log back into OSIO wondering why they aren't getting notifications/etc that we use their e-mail for, and see their e-mail is not verified in their profile.  They click a link to resend the e-mail so they try to verify the e-mail again.

**Comment by alexeykazakov** [comment]
>  the user has full access to the system even if their e-mail is unverified so they can get to this page?

Not full access. But most things will work. User can login, view profile, manage spaces and do a lot of other things. But some functionality won't be available. Can't opt-in to internal features. No notifications etc. It's up to particular module/functionality to decide if it should work for a user with unverified email.

> I think you're saying this is the flow:

Yes. The flow is correct.

**Comment by rohitkrai03** [comment]
[PR](https://github.com/fabric8-ui/fabric8-ui/pull/2777) fixes the issue which is merged. Closing it.
