### ISSUE TITLE
Delegate space resource creation from WIT to AUTH

### ISSUE THREAD

**Issue by sbose78** [fabric8-services/fabric8-auth#27]

**Comment by alexeykazakov** [comment]
Changed "Redirect space resource creation" to "Delegate space resource creation" to make sure there is no confusion. We are not going to use any http redirection here.

**Comment by sbose78** [comment]
Yes, delegate is what I implied.
Thanks for the correction.

**Comment by alexeykazakov** [comment]
We will also need to:
- copy existing space resources from WIT to Auth
- delegate all AuthZ from WIT to Auth
- redirect collaborators calls to Auth

**Comment by alexeykazakov** [comment]
Done.
