### ISSUE TITLE
Support token refresh in /api/token

### ISSUE THREAD

**Issue by kishansagathiya** [fabric8-services/fabric8-auth#270]
The `/api/token/refresh` endpoint is not compliant with the OIDC spoecification: token refresh should be achived with the same endpoint as token retrieval
(/api/token), but with different parameters (especially the `refresh_token` grant type), as described in the specification here:
http://openid.net/specs/openid-connect-core-1_0.html#RefreshingAccessToken

We will have to support both endpoints. So create refresh api at `/api/token` and reverse proxy `/api/token/refresh` to `/api/token`

**Comment by alexeykazakov** [comment]
To be clear. We can't remove the existing endpoint. It's still used by UI. We need to keep both until we update UI. Then we can remove the existing one.

**Comment by kishansagathiya** [comment]
`/refresh` api returns `AuthToken`, while `/token` api returns OAuthToken. I think `/refresh` should also return `AuthToken`,  http://openid.net/specs/openid-connect-core-1_0.html#RefreshTokenResponse

**Comment by sbose78** [comment]
@kishansagathiya let's leave /api/token/refresh as is, for now - since it's a critical piece of code called by the UI. 

In the `POST /api/token` , return `OAuthToken` as defined in the spec, and as already being done in the `Exchange` controller.
