### ISSUE TITLE
Implement the ListRoles by resource_type endpoint

### ISSUE THREAD

**Issue by sbryzak** [fabric8-services/fabric8-auth#288]
1.  listing only the roles for a specific resource type by setting the `resource_type` parameter. *done* as part of this task.

2. Listing all roles will be done in #348 

See [this section](https://docs.google.com/document/d/1qmpH8Yex0yKmcTauPqVoGmquRiEbab1E8fFf90tEw3A/edit#heading=h.kt11mbk2f6hw) of the detailed design document for details.

```
GET /api/role HTTP/1.1
Authorization: Bearer MHg3OUZEQkZBMjcx
```

```
HTTP/1.1 200 OK
Content-Type: application/json
...
[{  
   "role_id":"JA7X-PV9Z",
   "name":"collaborator",
   "resource_type":"openshift.io/resource/area"
   "scopes":["manage","view"]
},
{  
   "role_id":"P9A5-MX3H",
   "name":"administrator"
   "resource_type":"openshift.io/resource/area"
   "scopes":["admin"]
}]
```

**Comment by sbose78** [comment]
@alexeykazakov  @sbryzak can we make the API signature look like
`/api/roles` for all roles and `/api/resource_type/RESOURCE_TYPE_ID/roles` for possible roles for a resource type ?

**Comment by sbryzak** [comment]
I would be ok with this if we used the actual resource type name (e.g. "openshift.io/resource/area") instead of the uuid value, however the value would need to be URL encoded obviously. I'm saying this because it would also make sense to have an `/api/resource_type` endpoint that listed all the resource types.

**Comment by sbose78** [comment]
@sbryzak do you see any issues with using a query like this ( instead of multiple queries ) 
Do you recommend any optimization ? There are 4 tables involved, and there's no way this can be not expensive :( 

```
SELECT rts.NAME scope_name, 
       r.role_id, 
       r.NAME role_name 
FROM   resource_type_scope rts, 
       role_scope rs, 
       resource_type rt, 
       role r 
WHERE  rs.scope_id = rts.resource_type_scope_id 
       AND rs.role_id = r.role_id 
       AND rt.resource_type_id = r.resource_type_id 
       AND rt.NAME = 'openshift.io/resource/area'; 
```

of course, the results would need a bit of post processing to map create the 
```
{  
   "role_id":"JA7X-PV9Z",
   "name":"collaborator",
   "resource_type":"openshift.io/resource/area"
   "scopes":["manage","view"]
}
```
structure.

**Comment by sbryzak** [comment]
Which multiple queries would this be replacing?  You can see the query plan in postgres by using the EXPLAIN command, e.g:

```
postgres=# explain SELECT rts.NAME scope_name, 
postgres-#        r.role_id, 
postgres-#        r.NAME role_name 
postgres-# FROM   resource_type_scope rts, 
postgres-#        role_scope rs, 
postgres-#        resource_type rt, 
postgres-#        role r 
postgres-# WHERE  rs.scope_id = rts.resource_type_scope_id 
postgres-#        AND rs.role_id = r.role_id 
postgres-#        AND rt.resource_type_id = r.resource_type_id 
postgres-#        AND rt.NAME = 'openshift.io/resource/area'; 
                                        QUERY PLAN                                         
-------------------------------------------------------------------------------------------
 Hash Join  (cost=37.18..54.42 rows=485 width=54)
   Hash Cond: (rs.scope_id = rts.resource_type_scope_id)
   ->  Nested Loop  (cost=11.43..22.00 rows=485 width=38)
         ->  Nested Loop  (cost=0.00..2.05 rows=1 width=22)
               Join Filter: (rt.resource_type_id = r.resource_type_id)
               ->  Seq Scan on resource_type rt  (cost=0.00..1.02 rows=1 width=16)
                     Filter: (name = 'openshift.io/resource/area'::text)
               ->  Seq Scan on role r  (cost=0.00..1.01 rows=1 width=38)
         ->  Bitmap Heap Scan on role_scope rs  (cost=11.43..19.90 rows=5 width=32)
               Recheck Cond: (role_id = r.role_id)
               ->  Bitmap Index Scan on role_scope_pkey  (cost=0.00..11.42 rows=5 width=0)
                     Index Cond: (role_id = r.role_id)
   ->  Hash  (cost=17.00..17.00 rows=700 width=48)
         ->  Seq Scan on resource_type_scope rts  (cost=0.00..17.00 rows=700 width=48)
(14 rows)
```

I would need to compare this execution plan with the one for the other queries to have any idea about performance differences.

**Comment by sbryzak** [comment]
@sbose78 apologies, I did not look closely at the query earlier.  You should be able to use something like this (untested):

```
SELECT r.role_id,
r.name role_name,
array_to_string(array_agg(rts.NAME), ',') scopes
FROM   resource_type_scope rts, 
       role_scope rs, 
       resource_type rt, 
       role r 
WHERE  rs.scope_id = rts.resource_type_scope_id 
       AND rs.role_id = r.role_id 
       AND rt.resource_type_id = r.resource_type_id 
       AND rt.NAME = 'openshift.io/resource/area'
group by r.role_id, r.name;
```

**Comment by sbryzak** [comment]
By the way, the sequence scan (Seq scan) in the query plan is undesirable, we can improve this by adding an index to the name column in resource_type.

**Comment by sbose78** [comment]
Thanks @sbryzak `array_to_string(array_agg(rts.NAME), ',') scopes` was exactly what I was looking for yesterday ( without success ) !

Tried out the SQL and I get a neat 
```
               role_id                | role_name |       scopes       
--------------------------------------+-----------+--------------------
 48cc725d-7b96-4315-bd32-289848598f57 | owner     | read:org,write:org
(1 row)
```

> By the way, the sequence scan (Seq scan) in the query plan is undesirable, we can improve this by adding an index to the name column in resource_type.

Correct I'm gonna add the index.
