### ISSUE TITLE
Implement List Assigned Roles by Resource endpoint

### ISSUE THREAD

**Issue by sbryzak** [fabric8-services/fabric8-auth#289]
This endpoint lists the roles that have been assigned for a specified resource.

See [this section](https://docs.google.com/document/d/1qmpH8Yex0yKmcTauPqVoGmquRiEbab1E8fFf90tEw3A/edit#heading=h.eal3oploym7i) of the detailed design document for more information.

```
GET /api/resource/KX3A-39WE/roles HTTP/1.1
Authorization: Bearer MHg3OUZEQkZBMjcx
```

```
HTTP/1.1 200 OK
...
[{
   "identifier":"9XH4-BN3Y"
   "role_id":"JA7X-PV9Z",
   "role_name":"collaborator",
   "assignee_id":"1111-2222-3333-4444-AAAA-BBBB",
   "assignee_name":"john_smith",
   "assignee_type":"user",
   "inherited":"false"
},
{
   "identifier":"9XH4-BN7J"
   "role_id":"P9A5-MX3H",
   "role_name":"administrator",
   "assignee_id":"9999-8888-7777-6666-ZZZZ-XXXX",
   "assignee_name":"operations_team",
   "assignee_type":"team",
   "inherited":"true",
   "inherited_from":"P3Y8-17WB"
}]
```

**Comment by sbose78** [comment]
Breaking
For a specific `resource`, find the corresponding `resource type`.
For that `resource_type`, find the defined `roles`.
From those `role`s, find all the assignments from the `identity_roles` table.

**Comment by sbose78** [comment]
I think we should modify the API signature a bit - 

1. List available roles for a resource `/api/resource/RESOURCE_ID/roles` . This would yield the same results as `/api/resource_type/RESOURCE_TYPE_ID/roles`

This is going to be very handy when the UI asks for **What are the possible roles for RESOURCE_ID?** This will help render screens where the user is trying to assign someone a role. For the UI, asking by RESOURCE_ID is going to be a lot simpler compared to asking by RESOURCE_TYPE.

2. List assigned roles for a resource `/api/resource/RESOURCE_ID/roles/assigned`

What do you think @alexeykazakov @sbryzak ?

**Comment by sbose78** [comment]
Based on https://chat.openshift.io/developers/pl/beekriqewpdczyqb3dxoq7t6yc
The above is fine.

**Comment by sbose78** [comment]
Hi @sbryzak do we really need to return `assignee_name` ? I feel it's redundant :) 
Just the `assignee_id` should be good.

**Comment by sbryzak** [comment]
@sbose I feel the assignee_name is definitely useful when building the UI.  Imagine you want to list all of the roles that have been assigned for a resource - you query this endpoint and get a list of assignee_id values back.  Do you want to render this as simply uuid values? I don't think it would be very meaningful for the user ;)

**Comment by sbose78** [comment]
I understand the concern, @sbryzak .

>  you query this endpoint and get a list of assignee_id 

That's the case with most things in the UI at the moment. The UI makes a subsequent call to the `User API` to get user details from the Auth service APIs. :)

In fact in that case, I'm a bit torn into whether I should include the username instead :) we are not sure if UX would provide us screens for displaying the username or the fullName or both ( like github ). In fact, for OSO scenarios in future, they would definitely need the username.

**Comment by sbryzak** [comment]
Are there any other screens in the UI which currently show users?  What about work item comments, do they display the author's name? or their username?

**Comment by sbose78** [comment]
The collaborators' page show the name & the email address of every collaborator. ( though that page is gonna change for sure )

**Comment by sbryzak** [comment]
I guess we really need to ask the UI team about this. I'm certain there are other endpoints in the identity management API that will need to return users, so we should be consistent across the entire API in what we are actually returning.

**Comment by alexeykazakov** [comment]
I think we should return information which we know will be used by clients for sure (or most likely :)
If UI needs something we don't currently include then it's pretty easy to add this to our API responses later. We will need to adjust our API anyway when we start adopting it.
But removing stuff from results is another story. It's API breaking change.
