### ISSUE TITLE
Implement Create Organization endpoint

### ISSUE THREAD

**Issue by sbryzak** [fabric8-services/fabric8-auth#290]
This endpoint is used to create a new organization.

See [this section](https://docs.google.com/document/d/1qmpH8Yex0yKmcTauPqVoGmquRiEbab1E8fFf90tEw3A/edit#heading=h.myfuzmxxrg1y) of the detailed design document for more information.

```
POST /api/organization HTTP/1.1
Content-Type: application/json
Host: as.example.com
Authorization: Bearer 204c69636b6c69
...

{  
   "name":"Acme"
}
```

```
HTTP/1.1 200 OK
Content-Type: application/json
...
{  
   "organization_id":"4444-3333-5555-6666-HHHH-BBBB-AAAA"
}
```

This endpoint should execute two insert statements:

```
INSERT INTO RESOURCE (
		resource_id,
		parent_resource_id,
		owner_id,
		resource_type_id,
		name)
	VALUES (
		(new UUID value),
		null,
		(identity id of the user creating the organization),
		(select resource_type_id from resource_type where name = ‘organization’),
		‘Red Hat’
);
```

and

```
	INSERT INTO IDENTITY (
		identity_id,
		identity_resource_id)
	VALUES (
		(new UUID value),
		(the resource_id for the row we just created in the resource table)
	);
```

**Comment by sbryzak** [comment]
This issue should also introduce a new RESOURCE_TYPE record for organizations:

`INSERT INTO RESOURCE_TYPE (RESOURCE_TYPE_ID, NAME) VALUES (new UUID(), 'organization');`

For this resource type, we should also introduce an 'admin' scope to allow specific users to administer the organization:

`INSERT INTO RESOURCE_TYPE_SCOPE (SCOPE_ID, RESOURCE_TYPE_ID, NAME) VALUES (new UUID(), uuid of new organization resource type id, 'admin');`

**Comment by sbose78** [comment]
@sbryzak @alexeykazakov 
Since we have parent-child relationships for resources, do you think we should implement it in a way we store hierarchical area info? 
Something like this https://api.openshift.io/api/areas/e770c328-cbf4-482f-827b-a5176ea7d568

This reduces the number of look-ups. In postgres, its an 'ltree' datatype.
https://www.postgresql.org/docs/9.1/static/ltree.html

It gives us a lot of querying capabilities. 

( my comments aren't directly related to the new controllers I'm supposed to be implementing but I was trying to full-proof the design )

**Comment by alexeykazakov** [comment]
> Since we have parent-child relationships for resources, do you think we should implement it in a way we store hierarchical area info?

Good question. @sbryzak ?

I thought we also agreed that we don't need owner_id in our resources. Ownership is a permission/scope thing and we will grand admin role to the resource creator when resource is being created. But just in case, maybe we should store the creator as creator_id in the table? Just in case we would need this later for some reason.. WDYT?

**Comment by sbryzak** [comment]
The owner_id column has been removed in #301.  I am in support of adding a creator_id to the table, even though we won't use that data now, you're right in that it might be important later and it seems a shame to discard that information when we have it easily available at resource creation time.

**Comment by sbryzak** [comment]
@sbose78 sorry I missed your earlier question about using ltrees.  Right now I can't think of any benefit that it would give us, postgres already provides us with support for hierarchical queries which is more than sufficient when querying for permissions.
