### ISSUE TITLE
Endpoint to check if an external token is available

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8-services/fabric8-auth#312]
Currently the only way to check if a GitHub or OSO token is available for the user is to use /token?for=<resourceURL> endpoint to obtain the token.
But we not always need to obtain the token. Just checking if it's available is enough.

**Comment by sbose78** [comment]
From a 'cost of operation' perspective, this is the same as obtaining the token. Just that the response wouldn't have the token?

**Comment by alexeykazakov** [comment]
Yes. It's just about not returning the token.

**Comment by sbose78** [comment]
My suggestion is to have it something like `/api/token/status?for=...`

**Comment by alexeykazakov** [comment]
I like /token/status?for=
