### ISSUE TITLE
Verify OSO token status while retrieving OSO token in UI

### ISSUE THREAD

**Issue by sbose78** [fabric8-services/fabric8-auth#320]
Use `force_pull=true` in `/api/token` in UI

In the profile page, we show the status of whether OpenShiftOnline ( OSO ) and Github is connected.
To do so, the frond-end calls the 

- `https://auth.openshift.io/api/token?for=https://github.com` or 
- `https://auth.openshift.io/api/token?for=OSO_CLUSTER_URL`

 to check if the auth service has the user's OSO/Github token. If yes, Auth service returns the stored token along with a 200OK.

In many cases, the token stored with the Auth service might have become invalid for some reason. If you want Auth service to 'test' the token before it is returned, you need to pass an additional parameter called `force_pull=true`.

In the UI, the above is done while fetching the Github token status, but not for OSO yet.

This issue requires the above to be done for OSO as well.

Relevant API reference : http://swagger.goa.design/?url=github.com%2Ffabric8-services%2Ffabric8-auth%2Fdesign#!/token/token_Retrieve

The profile page 
![image](https://user-images.githubusercontent.com/545280/37019893-fe85acac-213f-11e8-90a3-d897da450354.png)

**Comment by sbose78** [comment]
already done.

**Comment by alexeykazakov** [comment]
Done in UI?

**Comment by sbose78** [comment]
Ah this was for UI. Right.

**Comment by alexeykazakov** [comment]
I almost did the same mistake when reading this issue. I updated the title and description to make it clear ;)

**Comment by rohitkrai03** [comment]
@sbose78 After going through the issue and code in UI I understand following - 

- There is a updateGithubStatus() method which is called on init.

- It gets token from auth API - https://auth.openshift.io/api/token?force_pull=true&for=https://github.com. 

- But we do not have any such update method for openshift account and need to add that.

Let me know if I am looking at it wrong.

**Comment by rohitkrai03** [comment]
@sbose78 @alexeykazakov [PR](https://github.com/fabric8-ui/fabric8-ui/pull/2613) raised for the issue.

**Comment by alexeykazakov** [comment]
Done.
