### ISSUE TITLE
We should be able to provision prod-preview users to prod OSO clusters

### ISSUE THREAD

**Issue by sbose78** [fabric8-services/fabric8-auth#349]
Currently the provisioning of OSO for prod-preview is self-service and the user's cluster is defaulted to free-stg . 

To enable specific prod-preview users to use prod OSO , we need to have an arrangement where something similar to online-registration can be used to provision prod OSO for a user on prod-preview.

prod OSO = { starter2 , starter 2a ..}

This would be needed as part of https://github.com/openshiftio/openshift.io/issues/2348

Update:

- [x] Add Prod clusters to preview Auth - https://github.com/fabric8-services/fabric8-auth/issues/370
- [x] Add prod-preview to the list of valid redirects in OSO Prod cluster.
- [ ] Fix OSO stg registration app so it use the same flow as prod OSO registration app.
- [ ] Make sure we can provision preview users to both free-stg and prod clusters in the stg OSO reg app.
- [ ] Switch OSIO UI (marketing page) to OSO stg reg app for signing up.

**Comment by alexeykazakov** [comment]
What if we add a drop down menu for all available clusters in user profile page available only to internal users (via feature toggle?) so users can update their cluster in the profile.
Then we just add prod clusters to the preview Auth config and users can switch between prod and stage clusters when needed.

@aslakknutsen any complications on the tenant service side?

**Comment by sbose78** [comment]
> What if we add a drop down menu for all available clusters in user profile page available only to internal users (via feature toggle?) so users can update their cluster in the profile.

In this case we have to consider if we support the use case of "one osio account talking to multiple clusters".

**Comment by alexeykazakov** [comment]
One OSIO account talking to one cluster. But the cluster can change.
1. User signs up for and provisioned to free-stg.
2. The same user (RHD account) signs up for and provisioned to east-2 cluster.
3. User can switch the cluster in users profile. It will only update the cluster in the profile.

**Comment by alexeykazakov** [comment]
We won't change UI. What we will do instead:
1. Add Prod clusters to preview Auth.
2. Fix OSO stg registration app so it use the same flow as prod OSO registration app.
3. Make sure we can provision preview users to both free-stg and prod clusters in the stg OSO reg app.
4. Switch OSIO UI (marketing page) to OSO stg reg app for signing up.

**Comment by sbryzak** [comment]
Out of date, closing.
