### ISSUE TITLE
Support privacy properties

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8-services/fabric8-auth#35]
Need to support privacy properties as shown in the following user profile mockup.
https://redhat.invisionapp.com/share/3ZBFATW28#/screens

The properties appear to be booleans for:

1. Display name in your public profile
2. Display email in your public profile
3. Display activity in your public profile
4. Display Spaces in your public profile
5. Display work items assigned in your public profile

We could temporarily store some extra properties in the user contextInformation object. However, I'm thinking we may want to make this part of the user's profile, along with properties like email, bio, etc.?

Moved from https://github.com/fabric8-services/fabric8-wit/issues/1288

**Comment by mindreeper2420** [comment]
@alexeykazakov @sbose78 For the user's email address, do we want it to be displayed by default, or hidden by default?

**Comment by alexeykazakov** [comment]
Good question... Hidden/private by default I guess?

**Comment by mindreeper2420** [comment]
I've created a wireframe that both matches the current User Profile layout and includes the ability to select Private or Public for the Email address. We are still reviewing it in UX, but feel free to add any comments that you have as well: https://redhat.invisionapp.com/share/F4F0D8FZA.

**Comment by alexeykazakov** [comment]
Thanks @mindreeper2420 ! Looks good.
