### ISSUE TITLE
API for notifying Auth about deprovisioned users

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8-services/fabric8-auth#353]
When OSO is deprovisioning a user it should notify OSIO. We should provide API on the OSIO Auth side for this.

Part of https://github.com/openshiftio/openshift.io/issues/2393

**Comment by alexeykazakov** [comment]
For now I think we could just add a field to the user/identity so we have the data. Later we can use it (call tenant service to deprovision users etc).

**Comment by sbose78** [comment]
On the tenant side, the functionality to de-provision needs to be built too, right?
@xcoulon , any idea?
