### ISSUE TITLE
existing spaces' migration : Create corresponding resources for existing spaces

### ISSUE THREAD

**Issue by sbose78** [fabric8-services/fabric8-auth#365]
### Task

1. Get list of all users ( we do this for updating tenants )
2. For each user, get all spaces `https://api.openshift.io/api/namedspaces/<username>`
3. For each space returned in (2), call `POST https:/auth.openshift.io/api/resources` 
4. For each space, calls Collaborators API to get list of space members, 
5. Call `Assign Role API` to add those users as 'contributors'. ( Q: to do so whose token should we use ? )

Part of https://github.com/fabric8-services/fabric8-auth/issues/359  

### Dependencies

- [x] #383 
- [x] #498 
- [ ] #512

**Comment by alexeykazakov** [comment]
- Drop existing space_resource table.

**Comment by sbose78** [comment]
Done for prod-preview and prod.
