### ISSUE TITLE
Create authz resource for new spaces

### ISSUE THREAD

**Issue by sbose78** [fabric8-services/fabric8-auth#366]
### Task

When a new space is being created using the existing `Spaces API`, call the resource creation authz APIs inside https://github.com/fabric8-services/fabric8-auth/blob/master/controller/space.go to create a new resource.

### Dependencies
The least that needs to be done on the Authz service:

- [x] Seed the `openshift.io/resource/space` resource_type
     Seed the `contributor`,`viewer`,`admin` role for the above resource_type
     Seed some scope for the `contributor` role (?) https://github.com/fabric8-services/fabric8-auth/issues/383

- [x] Add API to create a new Resource

**Comment by alexeykazakov** [comment]
> Seed the openshift.io/resource/space resource_type

As far as I remember we agreed on using openshift.io/resource/area resource type for spaces. Space == root area.
@sbryzak ?

**Comment by sbryzak** [comment]
@alexeykazakov That is correct, a space is an area.

**Comment by sbose78** [comment]
That sounds wrong to me, because `space` is not equal to root `area`. Whenever a space is created, a root iteration and a root area is created. 

Every `space` has a root `area`. Just like every `space` also has a root `iteration`.
A `codebase` belongs to a space, but does not belong to any area. So, there are things which can be associated with a `space` and not belong to the root `area` or any `area` - example `codebases`.

I would expect us to have resources like 
- openshift.io/resource/space
- openshift.io/resource/area
- openshift.io/resource/iteration

**Comment by sbose78** [comment]
All our discussions have been around 'adding users to space'. Do you think we should have separate resource types for areas/iterations ? The roles/scopes applied to a space can be used for areas/iterations since they are always associated with a space - just the way we do for workitems.

As an example, we can have scopes like `manage` which would employer the roles to create/update iterations & areas.

**Comment by sbryzak** [comment]
@sbose78 it was my understanding that there would be control over the privileges assigned within individual areas within a space, however I don't recall the specific use cases for this.  I guess it depends how an organization structures their spaces/areas.

**Comment by sbose78** [comment]
Exactly, thanks @alexeykazakov

**Comment by sbose78** [comment]
Done.

**Comment by sbose78** [comment]
Dependencies are done. Actual task remains.
