### ISSUE TITLE
Re-obtain GitHub and OSO tokens if they are not valid anymore

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8-services/fabric8-auth#38]
If there is something wrong with GitHub and OSO tokens we should force re-obtaining these tokens or re-linking accounts.

Moved from https://github.com/fabric8-services/fabric8-wit/issues/1351

**Comment by aslakknutsen** [comment]
A service that requires auth should respond with a www-authenticate header to allow the client to invoke the auth process to obtain the necessary auth.

* should be used for 'main' osio service auth as well as remote auth like OSO/GitHub
* should be used on both missing and expired auth

Expired might provide additional data to explain to the user what happened.

**Comment by sbose78** [comment]
@aslakknutsen @alexeykazakov Given that we now return the `www-authenticate` header, should we close this?

**Comment by aslakknutsen** [comment]
Yeah, we can close this. This https://github.com/openshiftio/openshift.io/issues/2118 tracks the overall impl across the different services.

**Comment by alexeykazakov** [comment]
@sbose78 currently we return www-authenticate for /token?for endpoint only. While https://github.com/openshiftio/openshift.io/issues/2118 is about overall implementation across OSIO we could/should use www-authenticate for other endpoints too.
So, yes, this particular issue can be closed. But we need to open another one(s) for Auth service to start using www-authenticate in other endpoints. For example if token is expired then we could return a `www-authenticate refresh` or `www-authenticate relogin`. If there is no token at all then `www-authenticate login` or something like this.

**Comment by alexeykazakov** [comment]
BTW here is an example from the OpenID Connect spec:
```
 HTTP/1.1 401 Unauthorized
  WWW-Authenticate: error="invalid_token",
    error_description="The Access Token expired"
```
It's just an example. Even OpenID Connect does not specify the format of such responses.

**Comment by sbryzak** [comment]
Out of date.
