### ISSUE TITLE
User profile page always rendering loggedInUser data

### ISSUE THREAD

**Issue by rohitkrai03** [fabric8-services/fabric8-auth#389]
### User profile page is always rendering loggedInUser data even if some other user profile page is opened. Related [issue](https://github.com/openshiftio/openshift.io/issues/2613)

- If another user profile is opened while logged in, data that is rendered is of logged in user rather than requested user.
- Navigation from any link or dropdown menu should change data as described above.

**Comment by rohitkrai03** [comment]
[PR](https://github.com/fabric8-ui/fabric8-ui/pull/2646) raised.

**Comment by alexeykazakov** [comment]
Merged.
