### ISSUE TITLE
Don't send email notifications to unverified emails

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8-services/fabric8-auth#397]
When a work item is created or changed we should not send email notifications to users with unverified emails.

**Comment by aslakknutsen** [comment]
Shouldn't the question be; Why do we allow 'unverified' email users access to the service?

**Comment by alexeykazakov** [comment]
It's a good question but I don't think we should block unverified email users until they verify the updated email. At least for now.
What if the user made an error when editing email and can't verify the email? How can user unblock himself? There is something for UX to think about. Btw for example you can continue using GitHub with unverified email.

Anyway we still need to check verified/unverified emails when sending notifications. I can trigger sending emails to the collaborators of the space even if some collaborators can't access OSIO.

**Comment by aslakknutsen** [comment]
I see what usecase, but why is the 'global known verified email' replaced by a 'unverified' one. 

If it's being replaced, and not just added (multi emails to 1 profile), shouldn't the verified email stay around until a new verified email can replace it ?

**Comment by aslakknutsen** [comment]
> I can trigger sending emails to the collaborators of the space even if some collaborators can't access OSIO.

Can you add an 'unverified' account as a Collaborator?

**Comment by alexeykazakov** [comment]
> I see that usecase, but why is the 'global known verified email' replaced by a 'unverified' one.
If it's being replaced, and not just added (multi emails to 1 profile), shouldn't the verified email stay around until a new verified email can replace it ?

Maybe. The whole "email" story need further work for sure. Do we want multiple emails? How it should look like. How we sync emails with the parent RHD account. Etc.

> Can you add an 'unverified' account as a Collaborator?

Yes. The only functionality limited to verified email account only atm is 1) ability to set feature level to "internal" and 2) space email notifications (this issue).
