### ISSUE TITLE
Ask for GitHub scopes when we really need them

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8-services/fabric8-auth#40]
Currently we ask users to link their GitHub accounts right after the first login. And we ask for full access to the user's GitHub account.
We should ask users to link GitHub when we actually need it (for example if only planner is used then we don't need GitHub account).
We also could ask for particular permissions/scopes instead of asking for full access. For example could ask for read access only until we really need to write something. Then we ask for write access. Etc.

So, our token management/storage API should support permission/scope elevation. Technically we could implement it via multiple GitHub links (one link per scope).

**Comment by sbose78** [comment]
Effectively the token management API should be now parameterized to accept scope information as well, and overwrite the existing/stored token.

**Comment by joshuawilson** [comment]
The part about asking for access when it is needed fits with the user story in the Platform and I think there is an issue or 2 in fabric8-ui.

**Comment by sbryzak** [comment]
No longer a priority.
