### ISSUE TITLE
After successful login user should be redirected to the original page. Not to home.

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8-services/fabric8-auth#401]
1. Logout from OSIO
2. Go to openshift.io/alexeykazakov or your own profile page
3. Click on login
4. You should be redirected to the original page - openshift.io/alexeykazakov but currently you are redirected to _home

**Comment by alexeykazakov** [comment]
The login request use correct redirect param. And auth service redirects to this correct URL but UI for some reason then changes location to _home.

**Comment by rohitkrai03** [comment]
[PR](https://github.com/fabric8-ui/fabric8-ui/pull/2661) raised.

**Comment by alexeykazakov** [comment]
@rohitkrai03 to be clear. We should redirect to whatever page there user was at when clicked on Login. In my steps-to-reproduce it's my profile page. But I guess we have the same issue regardless where I click on Login from.

**Comment by rohitkrai03** [comment]
@alexeykazakov Yeah. That is the desired behaviour and the PR fix will redirect to whatever page login was initiated from.

**Comment by alexeykazakov** [comment]
Good. Thanks. The original PR title was a bit confusing.
