### ISSUE TITLE
Show subscription status when unapproved user is trying to login

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8-services/fabric8-auth#419]
- [x] Add OSO token to Auth secret
- [x] Lookup for OSO subscription status using OSO API from Auth service when unapproved user is trying to login. Add this status to the URL as a param when redirecting unapproved user to https://openshift.io/not-authorized.html - https://github.com/fabric8-services/fabric8-auth/pull/422
- [x] Update https://openshift.io/not-authorized.html to show the subscription status - https://github.com/fabric8-services/fabric8-auth/issues/426

**Comment by alexeykazakov** [comment]
@catrobson we would need some UX help with proper wording to update https://openshift.io/not-authorized.html

**Comment by stacymcauliffe** [comment]
@alexeykazakov - Cat asked me to help with the content for this screen. A few questions:

**Comment by alexeykazakov** [comment]
@stacymcauliffe no, it's not about issues with credentials. We show this page when we recognize the user (user successfully logged into developers.redhat.com) but he/she is not approved in OSO/OSIO for some reason - user has not signed up yet or there is capacity issues in our clusters and the user is in the wait list.
Currently we just ask such users to login to manage.openshift.com to check the status (waiting approval) or sign up - https://openshift.io/not-authorized.html
But we now can pull the status from OSO and show this in that page - https://openshift.io/not-authorized.html instead of asking user to click on the button and check the status manually.
The statuses can be:
1 - Not signed up. So, user has to sign up.
2 - Waiting approval. We are in a manual approving mode for some reason (capacity issues maybe). User has to wait for approval. We will email when user is approved.
3 - Provision queued. Capacity issues most likely. Will take awhile to approve the user.

**Comment by alexeykazakov** [comment]
> Scenario 1-Not signed up, user has to sign up
Question: Would we need them to input their credentials again, or would we just provide a button for them to click?

It will be just a Sign-up button. So "Click Sign Up to register for access to OpenShift.io" looks good to me.

> Scenario 3: Provision queued
Question: Do we notify them once they're account is ready? I'm assuming the notification they receive is the same for scenarios 2 and 3

Correct.

So, all the messages for these 3 scenarios look good to me! Thanks!

**Comment by rohitkrai03** [comment]
@alexeykazakov Are there any UI changes from design side or we just showing status messages for all the 3 scenarios as mentioned above?

**Comment by alexeykazakov** [comment]
I assume there are no changes in design. Just different messages. @stacymcauliffe ?

**Comment by alexeykazakov** [comment]
Done.
