### ISSUE TITLE
Keycloak operation mode should be configurable via env vars.

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8-services/fabric8-auth#45]
It's follow up on https://github.com/fabric8-services/keycloak-deployment/pull/45

1. It should be possible to configure the clustered/standalone mode depending on env (both Cluster mode and the number of replicas bc it will fail if there is more then 1 replica in standalone mode)
2. There should be the default values (clustered mode + 3 replicas). If the env vars is not set in particular environment then the default ones are used.
3. Devs should be able to change the default values.

**Comment by vpavlin** [comment]
This can be done. You'l need to

1. Add `parameters` to your template (like IMAGE_TAG) for replicas and op mode
2. Set defaults (clustered + 3 replicas)
3. If there is a need to override add parameters to saas-openshiftio like analytics do it (https://github.com/openshiftio/saas-analytics/blob/master/bay-services/worker.yaml#L8)
4. If you need to override these params for a specific environment, use `environments` in saas-openshiftio yaml (https://github.com/openshiftio/saasherder#environments) We use `staging` and `production` (guess the names are selfexplanatory:) )

**Comment by hectorj2f** [comment]
Closing this issue! It was addressed by #46 and #106
