### ISSUE TITLE
Can't go to _home form _verifyEmail if verification failed

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8-services/fabric8-auth#465]
1. Open https://openshift.io/_verifyEmail?verified=false&error=some_error
2. Click on "Continue to my dashboard".
3. It navigates me to _home. But it's a blank screen. I have to refresh the page.

Navigation from https://openshift.io/_verifyEmail?verified=true works fine though.

**Comment by alexeykazakov** [comment]
I can't reproduce it in the latest prod deployment. It seems to be fixed now. Closing.

**Comment by rohitkrai03** [comment]
@alexeykazakov Yeah, this was the PR - https://github.com/fabric8-ui/fabric8-ui/pull/2779 which got merged yesterday.
