### ISSUE TITLE
Check OSO token validity on login

### ISSUE THREAD

**Issue by sbose78** [fabric8-services/fabric8-auth#480]
Upon login, in the Getting Started page, do a 'force pull' of the openshift online token status.

**Comment by aslakknutsen** [comment]
Could be done on 'login' in the backend as well could it not?

**Comment by sbose78** [comment]
The Getting Started page already has the 'logic' to auto-redirect to OSO login if the API returns a 401. Just need to add the `force_pull=true` to the existing request which goes out.

**Comment by alexeykazakov** [comment]
We could do the OSO verification step on the backend side during login but it would change the flow.. If there is no token available then we need to initiate the linking (do another round of redirects to OSO, etc). If the token is here but it's not valid anymore then I guess we should initiate linking/re-linking too and it can fail.. 
It's all doable but will require re-visiting our login flow in both backend and front-end.
Let's just quick-fix the current getting-started page (just add force_pull=true) first and later we can think about refactoring our login flow in backend and UI (get rid of getting started page/step).
