### ISSUE TITLE
When unapproved users are logging in then redirect to a page with proper explanation what to do 

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8-services/fabric8-auth#53]
If unapproved user tries to login we currently redirect to the OSIO/OSO registration page. We set this redirect URL via F8_AUTH_NOTAPPROVED_REDIRECT env var.
It can be confusing for users. Especially for user which have already registered and are waiting for approving.
We should create a dedicated page in openshiftio app with some proper explanation what is wrong and what user can do about it and redirect to that page instead.

**Comment by joshuawilson** [comment]
Why not let them go to the page directly? They can't edit it.

**Comment by alexeykazakov** [comment]
I'm not sure I understand the question.
1. User clicks on login button on OSIO
2. User is redirected to sso.os.io then to developers.redhat.com then back to api.os.io where we check if the user is actually approved or not. If not approved then we have two options. a) return an error or b) redirect to some page. We can't complete the registration to unapproved users. Currently we redirect to the OSO registration app but I think it make sense to create a separate page with some explanation and redirect to that page instead.

**Comment by joshuawilson** [comment]
Sorry I misread the task. I thought you were saying that we need to redirect users if they aren't logged in.

**Comment by alexeykazakov** [comment]
There is one more use case where such a page could help:
1. User has multiple developers.redhat.com accounts.
2. The user logged in to developers.redhat.com account different to the account used by OSIO.
3. The user tries to log in to OSIO. The user is redirected to RHD but since he/she is already logged in there (via wrong account) no credentials asked and user just logs in via the wrong unapproved account in OSIO. But because the user is not approved we redirect to the OSO registration page and don't allow to complete login.

The workaround for this case is to logout in both RHD and our Keycloak. The following URL opened in browser should help: https://api.openshift.io/api/logout?redirect=https%3A%2F%2Fopenshift.io

So, we can add this info with the link to that redirect page for unapproved users too.

**Comment by alexeykazakov** [comment]
@sbose78 btw, this info can be also useful for our FAQ ^

**Comment by alexeykazakov** [comment]
> There is one more use case where such a page could help:

Created a separate issue to fix that issue properly - https://github.com/fabric8-services/fabric8-auth/issues/64

**Comment by alexeykazakov** [comment]
@catrobson, could some one from the UX team help us with proper design and wording for such page? It's the page which we are going to redirect users who is trying to login but still awaiting approval.

**Comment by mceledonia** [comment]
Design for not authorized page here:

https://redhat.invisionapp.com/share/P7DZZ8QHK#/screens/258841923

**Comment by alexeykazakov** [comment]
@mceledonia thanks!

**Comment by alexeykazakov** [comment]
@mceledonia This is actually a bit more complicated. We do not know if unapproved user is in a waiting list  or not. So there are two scenarios:
1. User has never signed up and trying to login.
2. User has signed up but still in a waiting list and trying to login.

@luciddreamz is there any REST API available for us to check if user signed up in the registration app?

**Comment by luciddreamz** [comment]
Not having a REST API is one of our "security" features :)

Jacob Lucky
jlucky@redhat.com

**Comment by alexeykazakov** [comment]
Done.
