### ISSUE TITLE
Implement authorization workflow with RPT token

### ISSUE THREAD

**Issue by sbryzak** [fabric8-services/fabric8-auth#544]
- Support populating the RPT token with resource scopes for the requested resource.  
- Support caching of scopes for a configurable upper limit of resources.  
- Handle expiry of scopes, investigate possible "least recently used" policy for resource expiry (or alternatives)

## Workflows

Following are the proposed workflows, as contained in the [Detailed Design Document](https://docs.google.com/document/d/1qmpH8Yex0yKmcTauPqVoGmquRiEbab1E8fFf90tEw3A/edit#heading=h.dq33u6i6i8vt)

### Client has no RPT, requests resource
In this workflow, the client has not previously obtained an RPT, and requests access to a resource for the first time.

![image](https://user-images.githubusercontent.com/165507/42612742-5c766a68-85e0-11e8-9922-b86f88245b96.png)

1. 	The client requests access to a resource from the resource service, but does not provide an RPT (Requesting Party Token).

1.1. 	The Resource Server makes a request to the authorization service on the client’s behalf, and requests authorization for the resource.

1.1.1.	The authorization service queries the user’s privileges for the requested resource, and generates an RPT token including the user’s scopes for that resource - (this is an expensive operation). The new RPT token is returned to the resource service.

1.2.	The resource service introspects the RPT to determine the user’s privileges for the requested resource.  If the user has sufficient privileges for the operation they have requested, a successful response is returned to the client.  The RPT is returned to the client in the response header, so that the client may include it in subsequent requests in order to allow for more expedited authorization.

### Client has RPT, accesses previously authorized resource
In this workflow, the client has previously access a resource and has a currently valid (non-expired) RPT that includes the scopes for that resource.

![image](https://user-images.githubusercontent.com/165507/42612787-a317f004-85e0-11e8-9c1e-278793e802ae.png)

1. 	The client requests access to a resource from the resource service, and provides an RPT that it obtained from a prior request

1.1. 	The Resource Server introspects the RPT to check that it is valid (signed by the authorization service, not expired, contains appropriate scopes for the resource requested).

1.2.	The Resource Server makes a request to the authorization service to validate the RPT.  

1.2.1.	The authorization service validates the RPT to ensure that it has not been previously marked as outdated or otherwise invalidated.  This is a cheap operation.  On a successful validation the authorization service returns an “OK” response to the resource server, which in return returns the resource to the client.

### Client has RPT, accesses resource not previously authorized
In this workflow, the client has an RPT, but they attempt to access a resource that is not currently contained in the RPT.

![image](https://user-images.githubusercontent.com/165507/42612793-ae08c27c-85e0-11e8-8fdb-6fc3b42431fa.png)

1. 	The client requests access to a resource from the resource service, and provides an RPT that it obtained from a prior request

1.1. 	The Resource Server introspects the RPT to check that it is valid, however determines that the RPT does not contain privileges for the requested resource.

1.2.	The Resource Server makes a request to the authorization service to refresh the RPT, with privileges for the requested resource.  

1.2.1.	The authorization service queries the user’s privileges for the specified resource, and updates the RPT to include the scopes granted for that resource. The new RPT is returned to the resource service.

1.3.	The resource service introspects the new RPT, to determine whether the user has sufficient privileges to perform the requested operation on the resource.  If so, the operation completes as normal and the new RPT is returned to the client in the header.

**Comment by sbose78** [comment]
### RPT validation and invalidation

1. A table will be maintained to store < `RPT identifier` , `resourceID` , `identityID` , `isValid` >
2. validateRPT(..) will be a look-up on this table to check `if isValid = true` for `resourceID = X and RPT = Y`

**Strict approach**
- Whenever a user's scopes with respect to a resourceID changes, all records in the table associated with user is marked as invalid.
- Whenever a user has an association with a new resource, all existing records of that identity in table are marked as invalid.

This will cause validateRPT(..) to trigger the generation of an RPT everytime permissions change for a user.

**Lenient approach**
- Whenever the user's scopes with respect to a resourceID changes, all records in the table associated with the user & the resourceID, is marked as invalid.
- Whenever the user has an association with a new resource, existing records are *not* marked as invalid.

This will cause validateRPT(..) to trigger the generation an RPT *only* when a resource present in the RPT has changed.

**Comment by sbose78** [comment]
Notes about 'informing' the client/UI about the new RPT :
- Whenever the validateRPT(..) discovers the need of a new RPT to be generated, the new RPT would be returned to the resource server.
- The resource server must then return the new RPT in the response header.
- The UI needs to 'always' check if the response had a `Authorization: ` header. If yes, it needs to pick up the token and update the `AUTH_TOKEN` in the local storage with the new token.

This is where @rohitkrai03 will need to refactor the UI, to support looking for a response header in every response.

**Comment by sbose78** [comment]
Open questions:

- Should we generate the RPT at the time of login ?
- How many resources' should we include in the RPT ?
- If a user is associated with many resources, which ones do we choose to include in the RPT? ( recently accessed ones based on the content of `contextInformation` in the user/identity record?

**Comment by rohitkrai03** [comment]
@sbryzak @sbose78 All the workflows for RPT tokens seems fine and doable from the front end side. Its just explicit refreshing of tokens in front end is not clear. Since in the third workflow `Client has RPT, accesses resource not previously authorized` it says that 

> The Resource Server makes a request to the authorization service to refresh the RPT, with privileges for the requested resource.

This means that server would return and updated RPT token if client tries to access a resource not present in RPT earlier. So, client would just have to update RPT when server sends the response with updated RPT.  Is this correct?

**Comment by sbose78** [comment]
We have somewhat finalized the design:

- Implement the triggers that would invalidate a token. Example, whenever the assigned scopes change, we mark any RPT for an identity with that resource, as invalid/outdated. ( Need to document the list of triggers )

- `ValidateRPT(..)` endpoint would check if a token is outdated and return a 200 or a non-200

- `RefreshRPT(resourceID)` endpoint would generate a new RPT based on an existing RPT/user token , which would then *at least* include the scopes for the specified resourceID. Optimizations: ToBeAdded

( We did discuss whether we should have another `initializeToken(..)` endpoint , but for now, we will start with the above two )

**Comment by sbose78** [comment]
- Have only Refresh(...) endpoint.
- Have the `Refresh(..)` endpoint call the same service which would use the same the same login / 'db query' to determine if new token is to be generated. Do a create or update inside this service.
