### ISSUE TITLE
On acceptance of invitation, should we redirect to 'resource' home?

### ISSUE THREAD

**Issue by sbose78** [fabric8-services/fabric8-auth#546]
Example, On clicking on 'accept invite' to space/team link in my email, do you think we should redirect the user to the corresponding space home? Basically we would need to construct URLs based on the space name, user owning the space. 

Example, the space https://openshift.io/openshiftio/openshift_io/ is basically https://openshift.io/:owner/:spaceName

@sbryzak what are your thoughts on this?
@rohitkrai03 FYI. since you are gonna work with UX to get a design of 'invitation acceptance' page. We need to check what are their views on this.

**Comment by sbryzak** [comment]
I agree with this, it makes sense to me that accepting an invite to contribute a space or join a team would then take you to the space home page.

**Comment by sbose78** [comment]
Thanks @sbryzak . I was thinking along the same lines as well.

Effectively,
1. Check if resource type is space, if yes, call the `spaces API` to figure out the owner.
2. Check if resource type is team, if yes, lookup the parent resource ( aka space ), and then call the spaces API to figure out the owner.

Once the space owner is figured out, based on `config.GetEnvironment()` , construct the space URL ,
https://[environment]openshift.io/:ownerUserName/:spaceName

**Comment by sbose78** [comment]
@rohitkrai03  that is correct.

**Comment by rohitkrai03** [comment]
@sbose78 But what about the cases like 
- The user clicks on the link where his invitation has been rescinded.
- The user clicks on the link for second time where he has already accepted the invitation earlier.

**Comment by sbose78** [comment]
> The user clicks on the link where his invitation has been rescinded.
> The user clicks on the link for second time where he has already accepted the invitation earlier.

@rohitkrai03 Great question, sorry I wasn't clear. We would still need a proper redirected page to show that the invitation has expired.

**Comment by rohitkrai03** [comment]
@sbose78 So, for successful requests we redirect user to the space and for failed ones we show a landing page with error. Got it. Thanks.
