### ISSUE TITLE
List Invitations API

### ISSUE THREAD

**Issue by sbose78** [fabric8-services/fabric8-auth#553]
List invitations that have not been accepted.

**Comment by sbryzak** [comment]
Upon careful consideration I think we should probably have one endpoint for this, that accepts either the team or org ID, or the resource ID to which a user has been invited.  This would be consistent with the other invitation endpoints, of which we currently have:

`POST /invitations/:inviteTo` (Issue a new invitation)

`GET /accept/:acceptCode` (Accept an invitation)

Based on these, it makes sense that we use this endpoint to list invitations:

`GET /invitations/:inviteTo`

**Comment by sbose78** [comment]
@sbryzak Looks good to me.

**Comment by sbryzak** [comment]
Out of date, will address as part of notification service enhancements.
