### ISSUE TITLE
Should we add 'new' assignees and ignore the existing ones..

### ISSUE THREAD

**Issue by sbose78** [fabric8-services/fabric8-auth#556]
In our `Add Assignee` API request with a payload of multiple assignments, if one or more users already have the specified role(s) for the resource, we return a non 200 response and ignore the legitimate role assignments that could have taken place.

This is leading to this situation https://github.com/openshiftio/openshift.io/issues/4011#issuecomment-406180012

Should we instead do the legitimate role assignments , and ignore the ones already added?
Should we refactor our API to assign roles to those users who don't already have the role ? and not return an error in case somebody already has a role ?

@sbryzak

**Comment by sbose78** [comment]
https://github.com/openshiftio/openshift.io/issues/4011#issuecomment-406267794

I'm gonna go ahead and modify the API and return a 200 OK even if one assignment is possible, even though others are not possible because the assignments already exist.

FYI the 'Add many collaborators' API uses the `ForceAssign()` from the roles service.

Example, 
If out of 4 requested assignments, 1 is a legit case, and 3 already exist, the API should return a 200 with one assignment successful.
If out of N requested assignments, N already exist, the API would return a 409 conflict ( or anything which says 'resource already exists' )

**Comment by sbryzak** [comment]
@sbose78 That approach seems sensible to me, especially after reading the comments on the other issue.

**Comment by sbose78** [comment]
I'm making this change only for the 'Add collaborators' API for now.
