### ISSUE TITLE
Implement offline tokens natively in Auth

### ISSUE THREAD

**Issue by sbose78** [fabric8-services/fabric8-auth#577]
as a dependency of https://github.com/fabric8-services/fabric8-auth/issues/350

What are offline tokens?
https://fabric8-services.github.io/fabric8-auth/reference.html#_offline_tokens

### Token issuance:
If /api/login has `scope=offline_access` param,
generate a token with an expiry of 365 days.

### Token validation and usage
1. Validate if the token is an offline token using the "jti" claim, and if yes, check if it was last used within 30 days using the TOKEN_ACCESS_LOG table ( https://www.dbdesigner.net/designer/schema/98194 )
2. If yes, generate a new access token and return it.

Dependencies:

- [x] TOKEN table https://github.com/fabric8-services/fabric8-auth/issues/582

**Comment by sbose78** [comment]
( move to different place.. )

1. Store access/refresh/offline tokens in TOKEN table ( to be renamed from RPT token table )
2. Add a new token access log
3. Use the info in (2) for offline token usage

**Comment by xcoulon** [comment]
Offline tokens will not be supported in the future, so no need to implement this feature in `fabric8-auth`
