### ISSUE TITLE
Disconnect keycloak and make OAuth login more generic.

### ISSUE THREAD

**Issue by hemanik** [fabric8-services/fabric8-auth#583]
## Expected behavior

- Update the codebase to rename all references to `Keycloak`  types/services with something more generic (maybe OAuth2Service ?)
- Make the ClientID and Secret configurable using an OAuth server that returns a JWT as an access token.

## Actual behavior

At the moment Auth relies on Keycloak for the ClientID and Secret for the login process.

**Comment by sbose78** [comment]
https://github.com/fabric8-services/fabric8-auth/pull/618 Userinfo lookup has been made IDP-agnostic. References to keycloak remain in some places but they are harmless and can be gradually removed.
