### ISSUE TITLE
Cleanup of tokens

### ISSUE THREAD

**Issue by sbose78** [fabric8-services/fabric8-auth#595]
We will having a lot of invalid/expired tokens in our TOKEN table, we need to design a generic 'work thread' which cleans this up time-to-time.

The effort around this work should ensure that the code written for this should be extensible for any kind of auth service related cleanup.

**Comment by xcoulon** [comment]
could we consider having a Job/batch for this ?

**Comment by sbryzak** [comment]
We also have to clean up old entries in the `oauth_state_references` table.

**Comment by sbryzak** [comment]
Still a priority as of Jan 2019

**Comment by alexeykazakov** [comment]
@sbryzak it's already done, right?

**Comment by sbryzak** [comment]
Yes, already done.
