### ISSUE TITLE
401 intercepter not working properly for re-login workflow

### ISSUE THREAD

**Issue by rohitkrai03** [fabric8-services/fabric8-auth#597]
A token refresh call with 401 status and `www-authenticate` header does not trigger re-login as intended.

**Comment by rohitkrai03** [comment]
Quick Note - This is happening due to the recent move to `HttpClient` in `fabric8-ui` which is not completely done yet. Solution involves changes to `Fabric8HttpService` regarding `HttpClient`.

**Comment by rohitkrai03** [comment]
@xcoulon This one can only happen after the angular upgrade. Will add it to milestone when i pick it up after that. Is that ok?

**Comment by xcoulon** [comment]
sure! thanks for letting me know, @rohitkrai03 ;)
