### ISSUE TITLE
Service layer for validating & refreshing RPT

### ISSUE THREAD

**Issue by xcoulon** [fabric8-services/fabric8-auth#614]
Reference: https://openshift.io/openshiftio/Openshift_io/plan/detail/111
See also: #544

**Comment by sbose78** [comment]
being taken care of as part of https://github.com/fabric8-services/fabric8-auth/pull/561

**Comment by sbryzak** [comment]
Out of date, @xcoulon I believe this has already been implemented, if this is incorrect please let me know.
