### ISSUE TITLE
Handle case where a user has multiple roles on resources

### ISSUE THREAD

**Issue by xcoulon** [fabric8-services/fabric8-auth#622]
This is a follow-up for https://github.com/fabric8-services/fabric8-auth/issues/545 in which an endpoint lists all resources of a given type for which the user has a role in. But the current response does not properly handles the case where the user has multiple roles on the same resource:

````
 {
     "data": [{
         "attributes": {
             "role": "contributor",
             "scopes": ["contribute", "view"]
         },
         "id": "18c25d66-b160-4c4f-9705-22f68dcca102",
         "type": "spaces"
     }, {
         "attributes": {
             "role": "admin",
             "scopes": ["contribute", "manage", "view"]
         },
         "id": "18c25d66-b160-4c4f-9705-22f68dcca102",
         "type": "spaces"
     }]
 }

````

**Comment by sbryzak** [comment]
Why is this endpoint returning role names, or scopes for that matter?  What is the use case for this?

**Comment by xcoulon** [comment]
closing since https://github.com/fabric8-services/fabric8-auth/issues/629 is about removing the role(s) and scope(s) from the response anyways.
