### ISSUE TITLE
Remove redirect params from Issue invitation service

### ISSUE THREAD

**Issue by sbose78** [fabric8-services/fabric8-auth#642]
We should change 

```
Issue(ctx context.Context, issuingUserId uuid.UUID, inviteTo string, redirectOnSuccess string, redirectOnFailure string, invitations []invitation.Invitation) error {
```

to 

```
Issue(ctx context.Context, issuingUserId uuid.UUID, inviteTo string, invitations []invitation.Invitation) error {
```

The redirect urls should be part of the invitation instances in `invitation []invitation.Invitation`

**Comment by xcoulon** [comment]
Good catch, especially if each invitation has its own `success` and `failure` URLs!

**Comment by sbose78** [comment]
Thanks to @sbryzak :)

@xcoulon @dipak-pawar : 
Note: each invitation request payload currently supports only one set of redirect URLs.

**Comment by dipak-pawar** [comment]
@sbose78: Thanks for the info. But this is by design because I don't see any use case where from ui you want to invite multiple users and redirect them to different urls. If we have any valid use case we can change this in future to support different endpoints for each invitation
