### ISSUE TITLE
Store generated `session_state` in refresh token

### ISSUE THREAD

**Issue by xcoulon** [fabric8-services/fabric8-auth#669]
This is a follow-up of https://github.com/fabric8-services/fabric8-auth/issues/667 in which each new access token has a new `session_state` claim value.
To keep the same value for every subsequent access token, this claim should also be kept in the refresh tokens, which are always passed to generate a new access token.

**Comment by alexeykazakov** [comment]
session_state is not used anymore. Closing as outdated.
