### ISSUE TITLE
Add API to ban users

### ISSUE THREAD

**Issue by sbose78** [fabric8-services/fabric8-auth#678]
PATCH /namedusers/{username}/ban
Should call the API here https://github.com/openshift/online-registration#banning-users 
Use online-reg-app server URL as here https://github.com/fabric8-services/fabric8-auth/blob/master/configuration/configuration.go#L118

Note: We are yet to get the privileges to ban in the user that makes this call https://github.com/fabric8-services/fabric8-auth/blob/master/configuration/configuration.go#L119

**Comment by dipak-pawar** [comment]
@sbose78 https://github.com/openshift/online-registration#banning-users is not valid

**Comment by sbose78** [comment]
You need to be added to the org :)
