### ISSUE TITLE
Creating User in WIT called 2 times

### ISSUE THREAD

**Issue by dipak-pawar** [fabric8-services/fabric8-auth#684]
If we follow following steps `WITService().CreateUser(ctx.Context, identity, identityID.String())` is called two times.
1. when we hit POST /users/create (using manage.openshift.com or manually) 
2. User tries to login for the first time.

Currently, we are not creating user and identity for local setup where we don't want user to hit `/user/create` endpoint locally using SA token and getting required identityID from IDP.

We should support this use case as well while working on this issue

**Comment by sbose78** [comment]
> Currently, we are not creating user and identity for local setup where we don't want user to hit /user/create endpoint locally using SA token

Well locally too, user should be adding herself using the sa token ( needs docs though )

**Comment by sbose78** [comment]
I feel a bit uncomfortable having an `if dev mode` block to support a dev mode flow inside a production code flow, which would have a significantly different behavior.

Currently, the developer anyway couldn't login without us approving on keycloak. 
Now the developer can approve herself and login - otherwise they can always use the dev mode /api/token/generate for getting tokens.

What we could possibly do is, 
Add a curl command to the readme along with the local SA token. ( so that user doesn't have to generate it ).

**Comment by sbose78** [comment]
Or, maybe pass a username to /api/token/generate which would create a new record in the DB. At least that would limit the dev-only code in one place.

**Comment by dipak-pawar** [comment]
@sbose78, I will change my mind, because if we allow a user to do the same process which we are doing at this point, it'be uniform for all the environment(dev, prod-preview, prod). I will update the documentation with simple curl command to use approve user locally in case someone needs it. 

Thanks for your input @sbose78

**Comment by xcoulon** [comment]
> @sbose78, I will change my mind, because if we allow a user to do the same process which we are doing at this point, it'be uniform for all the environment(dev, prod-preview, prod). I will update the documentation with simple curl command to use approve user locally in case someone needs it.
> 
> If we have this thing ready we can get rid out of `/generate` api, as user can create token locally as well without asking for explicit approval
> 
> Thanks for your input @sbose78

Great! Good point on keeping the `dev mode` specifics as minimal as possible. Since we have a pair of public/private keys for the dev mode, we should be able to generate an `SA` token for dev and provide it as part of the `curl` command doc, shouldn't we?

**Comment by sbose78** [comment]
> we should be able to generate an SA token for dev and provide it as part of the curl command doc, shouldn't we?

absolutely!
