### ISSUE TITLE
Initiate a new service for admin console

### ISSUE THREAD

**Issue by xcoulon** [fabric8-services/fabric8-auth#687]
Initiate a new back-end service with minimal functionalities for now:

- [ ] Login 
- [ ] API to search users (https://openshift.io/openshiftio/Openshift_io/plan/detail/739). For this features, the admin service should simply proxy/forward the request to the `auth` service. 

Ideally, the project could be bootstrapped with http://github.com/fabric8-services/fabric8-starter so we can reuse pkgs from http://github.com/fabric8-services/fabric8-common

Also, the users authorized to log into the service should be limited, ideally using roles in auth.

**Comment by xcoulon** [comment]
great, thanks @sbryzak

**Comment by sbryzak** [comment]
New repo is here: [https://github.com/fabric8-services/admin-console](https://github.com/fabric8-services/admin-console)

**Comment by sbose78** [comment]
For SD:
Setup a new DB on RDS: https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2365
Setup sub domain for service: https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2366

Let's roll with `api.adminconsole.openshift.io` so that our UI would be `adminconsole.openshift.io`

**Comment by sbryzak** [comment]
I think that simply `admin.openshift.io` would be sufficient, the "console" bit seems superfluous.

**Comment by sbose78** [comment]
Fine with me.

https://github.com/openshiftio/saas-openshiftio/pull/1080/files

**Comment by xcoulon** [comment]
Closing as backend service is now available at https://admin-console.api.prod-preview.openshift.io and https://admin-console.api.openshift.io with support for user search.
