### ISSUE TITLE
Add admin during resource registration

### ISSUE THREAD

**Issue by sbose78** [fabric8-services/fabric8-auth#693]
Should we modify the resource registration API to also include the identityID of the user who would have the scope to manage roles for the specific resource? The user would be assigned the `admin` ( or something similar ) for that resource at the time of resource registration.

Without this, there's no way to assign a role to an arbitrary user to a resource, after resource registration.

**Comment by sbose78** [comment]
@sbryzak , what do you think?

**Comment by sbryzak** [comment]
Let's add a new nullable column to the `RESOURCE_TYPE` table, called `DEFAULT_ROLE_ID`, with a foreign key constraint to the `ROLE.ROLE_ID` column.  Then, when registering a new resource, the resource service will look for a value in this column, and if found, assign the specified role to the creating user for the new resource.  This change also requires that we pass in the current user's `IDENTITY_ID` value as a parameter to the `resource_service.Register()` function.
