### ISSUE TITLE
fragment part of the `redirect_uri` not managed correctly by the `authorize` endpoint.

### ISSUE THREAD

**Issue by davidfestal** [fabric8-services/fabric8-auth#695]
## Expected behavior

When calling the `authorize endpoint with the following parameters:
```
https://auth.openshift.io/api/authorize?client_id=740650a2-9c44-4db5-b067-a3d1b2cd2d01&redirect_uri=https%3A%2F%2Fche.openshift.io%2Fdashboard%2F%23%2Ffactories&state=e718826e-c356-45dd-825a-59a4b1f22299&response_mode=fragment&response_type=code&scope=openid
```
(please note that, once decoded, the `redirec_uri` is
`https://che.openshift.io/dashboard/#/factories`),

we would expect the browser to be redirected to the requested `redirecr_uri` followed by the additional fragment parameters corresponding to the OIDC authentication results (code, state, etc ...), just like that:
```
https://che.openshift.io/dashboard/#/factories&code=uss.funn2d7pd-Mk4aj1wcZ7h231Tuk6rQROEdbgYq_W1BA.a59c3250-b5d4-44fc-be8d-50b71b843974.98447a27-40de-450b-a987-1ddc97730839&state=e718826e-c356-45dd-825a-59a4b1f22299
```

## Actual behavior

Instead, the fragment part of the initial `redirect_uri` is __not included__ in the final url the browser is redirected to, as show by the following URL where the browser is really redirected to in previous example above:  
```
https://che.openshift.io/dashboard/#code=uss.funn2d7pd-Mk4aj1wcZ7h231Tuk6rQROEdbgYq_W1BA.a59c3250-b5d4-44fc-be8d-50b71b843974.98447a27-40de-450b-a987-1ddc97730839&state=e718826e-c356-45dd-825a-59a4b1f22299"
```

## Steps to reproduce the problem

Just point the browser to `https://che.openshift.io/dashboard/#/factories`, and see that, after login through `fabric8_auth`, the final page is `https://che.openshift.io/dashboard/#/`

## Specifications

This occurs on the production version of `fabric8_auth`

**Comment by davidfestal** [comment]
cc @alexeykazakov, since we discussed the problem before concluding this might be a bug on the `fabric8_auth` that has been exposed by the following `rh-che` commit: https://github.com/redhat-developer/rh-che/commit/5fc0c807cd25773a79027cfc350fb03712b65f2b

**Comment by davidfestal** [comment]
FYI, this is the root cause of the following RhChe issue reappearing in production several days ago: https://github.com/redhat-developer/rh-che/issues/839#issuecomment-429853652
However this time this is even more critical than the first issue, since __all the types of factory links__ will simply not work (be silently ignored, so that the user is brought simply to the dashboard home instead).

**Comment by sbose78** [comment]
Ack. Taking a look.

**Comment by davidfestal** [comment]
Thanks @sbose78  !

**Comment by sbryzak** [comment]
I've been refactoring the authorize controller, @sbose78 if you determine the problem please touch base with me so we can integrate the fix.

**Comment by sbose78** [comment]
@sbryzak 
https://github.com/fabric8-services/fabric8-auth/pull/697
https://github.com/fabric8-services/fabric8-auth/pull/696
