### ISSUE TITLE
Make collaborators' settings page visible to all admins

### ISSUE THREAD

**Issue by sbose78** [fabric8-services/fabric8-auth#699]
@rohitkrai03 

Today, the collaborators page is visible to only the space creator/owner. How about we make it visible for all space admins which is the intent, anyway.

Here's the simplest way to accomplish this:
1. Call GET `/api/resource/:resourceID/scopes` to see if the user has a `manage` scope on the resource.
2. If yes, show the collaborators page.

@sbryzak @xcoulon  Thoughts?

**Comment by rohitkrai03** [comment]
@sbose78 Seems like a good solution to start with. Once, the RPT workflow comes in we can replace this call with it.

**Comment by xcoulon** [comment]
that seems like a very good idea, indeed @sbose78.
