### ISSUE TITLE
Add support for adding admins from the Collaborators UI

### ISSUE THREAD

**Issue by sbose78** [fabric8-services/fabric8-auth#700]
@rohitkrai03 

Even though we are gonna be adding the full-fledged permissions UI later on, I was wondering if we could have a way in the Collaborators UI ( from the collaborators list? ) to make an existing collaborator an `admin` by calling the following API, today.

http://swagger.goa.design/?url=github.com%2Ffabric8-services%2Ffabric8-auth%2Fdesign#!/resource_roles/resource_roles_assignRole
```
PUT /resources/{resourceID}/roles

{
  "data": [
    {
      "ids": [
        "identityID...1",
        "identityID...2",
      ],
      "role": "admin"
    }
  ]
}
```

Of course, I'm suggesting something that would need negligible/minimal UI & UX iteration since that would anyway go away.

What do you think @sbryzak @dipak-pawar @xcoulon ?

**Comment by rohitkrai03** [comment]
@sbose78 This should be easily doable. We can just add one action button for making a collaborator `admin` in the collaborators list. Also, the creator or other admins will be able to make other users admin.

**Comment by xcoulon** [comment]
yes, by checking permissions in the RPT token, you could do that, indeed.

**Comment by rohitkrai03** [comment]
@xcoulon We can use RPT token now? I thought the resource servers need to implement that first?

**Comment by rohitkrai03** [comment]
@sbose78 Yes, we discussed this in our weekly sync meeting yesterday and decided to go with the Audit token API. That way when resource servers implement the workflow we don't need to change any code.

**Comment by sbose78** [comment]
Added some docs to use RPT: https://fabric8-services.github.io/fabric8-auth/reference.html#_determining_the_scope_using_rpt_tokens
