### ISSUE TITLE
Space owner can remove himself as admin

### ISSUE THREAD

**Issue by rohitkrai03** [fabric8-services/fabric8-auth#717]
Related to https://github.com/fabric8-services/fabric8-auth/issues/700

For a space that i am a owner, I am able to assign myself `contributor` role and there by removing myself as an `admin`.

API - http://swagger.goa.design/?url=github.com%2Ffabric8-services%2Ffabric8-auth%2Fdesign#!/resource_roles/resource_roles_assignRole
Request apyload - 

```
{
ids: [ '70295efa-b832-44c6-ab39-2f032465cc96' ]
role: 'contributor'
}
```

**Comment by alexeykazakov** [comment]
We need to think about some protection to avoid the situation when some resource doesn't have any admins at all.

**Comment by alexeykazakov** [comment]
cc: @sbryzak

**Comment by sbose78** [comment]
Yes, shooting self(admin) in the foot is OK but let's ensure we have at least one 'admin' for the space.

**Comment by xcoulon** [comment]
we should keep the space owner as an admin in any case.

**Comment by joshuawilson** [comment]
The space owner can't leave, they are tied to the space. But transferring ownership makes sense. 

If the Space owner "leaves", that only happens when the delete the space or get their account deleted. Unless you mean they just stop working in the space.

**Comment by sbose78** [comment]
> Unless you mean they just stop working in the space.

Yes, this is what I implied.

**Comment by joshuawilson** [comment]
so then we need a provision for transferring ownership or at a minimum setting a new admin

**Comment by xcoulon** [comment]
> so then we need a provision for transferring ownership or at a minimum setting a new admin

there's already what's needed to promote a user as an admin on a space, isn't it? What's missing is a mean to transfer ownership, both in the UI and in the backend services, AFAIK

**Comment by joshuawilson** [comment]
I was thinking of a way to do it when the owner goes inactive and there is no one to promote a user to admin.

Adding transfer of ownership is a different issue but useful too.

**Comment by alexeykazakov** [comment]
AuthZ doesn't care about space ownership IMO. Ownership is outside of AuthZ. AuthZ cares about roles/scopes only. If we want to manage ownership by Auth then we have to create a new role for that but IMO we don't need it for now.
Ideally Auth should make sure that resources has at least one admin. Otherwise it will be possible to create "orphan" resources. But it can be tricky or too expensive because resource can be hierarchical and even if some resource doesn't have any direct admins the parent resource can have an admin.
Maybe it's better to protect it in UI for now...

**Comment by joshuawilson** [comment]
It should be simple enough to protect the user from removing themselves from the admin role.

We still have the question of transfer of ownership, that can't be done in the UI.
