### ISSUE TITLE
Protection API Token (PAT) / Service Account Issuance and Validation

### ISSUE THREAD

**Issue by sbryzak** [fabric8-services/fabric8-auth#72]
This issue is for tracking work relating to the issuance and validation of Protection API Tokens (PAT).

- [x] Allow service accounts to be configured - #153 
- [x] SA token issuance (login) endpoint - #154

**Comment by fche** [comment]
@alexeykazakov, can you help point to the new API call(s) to enumerate tenants?

**Comment by alexeykazakov** [comment]
@fche enumarate tenants API is not part of Auth. It's something for https://github.com/fabric8-services/fabric8-tenant service to implement. cc: @aslakknutsen 
What Auth can help you with is API to obtain a service account token which can be used to access the tenant service.

**Comment by fche** [comment]
Thanks, that is https://github.com/fabric8-services/fabric8-tenant/issues/369.
