### ISSUE TITLE
API to remove a inactive user and all related db entries.

### ISSUE THREAD

**Issue by dipak-pawar** [fabric8-services/fabric8-auth#733]
Develop api endpoint to remove inactive user and all relatest db entries which should call to other services to clean up resources belongs to that user.

**Comment by xcoulon** [comment]
I believe that this is going to be addressed in the [User Deactivation Epic](https://github.com/fabric8-services/fabric8-auth/issues/774)

**Comment by alexeykazakov** [comment]
@xcoulon agree. Closing this one.
