### ISSUE TITLE
 Copy already existing Space Resources entities from WIT DB to Auth

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8-services/fabric8-auth#75]

**Comment by alexeykazakov** [comment]
Blocked by https://github.com/fabric8-services/fabric8-auth/issues/65

**Comment by joshuawilson** [comment]
why do you want to copy these?

**Comment by alexeykazakov** [comment]
A Space Resource is just a record of Space ID and Keycloak Resource ID. We use this table to track what Keycloak Resource represents the Space.
As soon as https://github.com/fabric8-services/fabric8-auth/issues/27 merged Keycloak Resource IDs for **new** Spaces will be stored in both WIT and Auth DBs. The next step would be a copying of existing Keycloak Resource IDs from WIT to Auth (this issue is exactly that step). So both DBs will be in sync. After that we can start using Auth for space authorization and as the final migration step we will drop Keycloak Resource ID table in the WIT DBs.

**Comment by joshuawilson** [comment]
thanks

**Comment by alexeykazakov** [comment]
Done
