### ISSUE TITLE
Contract tests related PR builds conflicts with regular PR check builds.

### ISSUE THREAD

**Issue by pmacik** [fabric8-services/fabric8-auth#800]
Steps to reproduce:
Create a new PR and when `ci.centos.org PR build` (not `ci.centos.org PR build (contract tests)`!) status appears, click on Details to see that it opens the contract test job instead. Then it will report it as green. But meanwhile, the actual `ci.centos.org PR build` job is running too. And when it's done it will update/override the status in the PR.

**Comment by pmacik** [comment]
The problem seems to be that the status context message in contract tests' job's definition is not correctly set to `ci.centos.org PR build (contract tests)` and it has the default value of `ci.centos.org PR build` that collides with the regular PR job.

https://github.com/openshiftio/openshiftio-cico-jobs/pull/972 should fix that.

**Comment by pmacik** [comment]
The PR was merged and took effect. And it looks it works - there are now separate PR checks each with it's own jenkins job.

@xcoulon, @alexeykazakov Could you please verify, the issue was fixed? Thanks

**Comment by alexeykazakov** [comment]
Seems to work fine now. Thanks!
