### ISSUE TITLE
get a working release pipeline

### ISSUE THREAD

**Issue by jstrachan** [fabric8-services/fabric8-auth#86]
so we can reuse fabric8-auth upstream in fabric8-platform.

Typically we run `make release` which then generates a github release of the binary then we use the `Dockerfile` to create a versioned image. e.g. like these projects https://github.com/fabric8-services/fabric8-wit, https://github.com/fabric8-services/fabric8-tenant

e.g. adding something like this
https://github.com/fabric8-services/fabric8-tenant/blob/master/Makefile#L268-L269

an extra nice to have is to generate a github release too which lets folks download the binary if they want like we do for other go based projects
* https://github.com/fabric8io/exposecontroller/ generates [releases](https://github.com/fabric8io/exposecontroller/releases)
* https://github.com/fabric8io/gofabric8/ generates [releases](https://github.com/fabric8io/gofabric8/releases)

by adding something like this to the `Makefile`
https://github.com/fabric8io/exposecontroller/blob/master/Makefile#L75-L81

**Comment by alexeykazakov** [comment]
I created a new issue to cover the github release generation - https://github.com/fabric8-services/fabric8-auth/issues/88
