### ISSUE TITLE
Generate github releases

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8-services/fabric8-auth#88]
Extracted from https://github.com/fabric8-services/fabric8-auth/issues/86:

> an extra nice to have is to generate a github release too which lets folks download the binary if they want like we do for other go based projects
> 
> https://github.com/fabric8io/exposecontroller/ generates releases
> https://github.com/fabric8io/gofabric8/ generates releases
> by adding something like this to the Makefile
> https://github.com/fabric8io/exposecontroller/blob/master/Makefile#L75-L81

**Comment by sbryzak** [comment]
No longer relevant.
