### ISSUE TITLE
add an `/api/status` health check endpoint like we do for WIT / F8 tenant?

### ISSUE THREAD

**Issue by jstrachan** [fabric8-services/fabric8-auth#89]
we should have some endpoint we can use for liveness/readiness checks

**Comment by jstrachan** [comment]
DOH - just spotted its at `/status` :)

**Comment by alexeykazakov** [comment]
Not sure what you spotted :) but we do have it exactly in the same path like we have in WIT - /api/status (not just /status). For example: https://auth.openshift.io/api/status

**Comment by jstrachan** [comment]
thought it was liveness check URL that was causing the auth pod to get killed on openshift; turns out to have been the change of port from 8080 -> 8089 - no worries - all sorted now!
