### ISSUE TITLE
support other git repository providers?

### ISSUE THREAD

**Issue by jstrachan** [fabric8-services/fabric8-auth#93]
It'd be awesome if we could add custom git providers (gitlab servers, atlassian stash, gogs/gitea etc) and then link to them so that we can use the server URL + token to work with gitlab/stash/gogs/gitea git repos

to start with we could maybe assume there's a local kubernetes Service for gitlab / gogs / gitea / stash; but over time supporting different URLs would be nice (so they could run inside k8s or outside)

**Comment by alexeykazakov** [comment]
It's pretty easy to make the only Git provider configurable and use GitHub by default. Is it good enough for you? Or you want to be able to have multiple Git providers? We are planing to support multiple Git providers too but it's for future.

**Comment by jstrachan** [comment]
I think we're gonna have to support different git providers really; plus each provider requires different characteristics (e.g. URLs for cloning, ways to create PRs and whatnot).

The new auth API to query tokens by URL will help being able to retrieve tokens for different git providers; the tricky bit is getting git providers like gogs / gitea / gitlab / stash to use KeyCloak for SSO so that folks can sign in and use the UIs of the git providers using SSO

**Comment by alexeykazakov** [comment]
Yeah, we plan to support different git providers. But my question is if having just one configurable git provider for now is good enough or it doesn’t help and we need to be able to add/set up multiple providers.

Currently there is just one GitHub provider (it points to GitHub) with client id and secret passed via env vars.
We can modify it pretty easily to a generic Oauth2 provider so this only provider points to GitHub by default but it’s URLs can be set via env vars. Then it will be possible to use it for other git providers. But only one provider.

If it doesn’t help and fabric8 platform need to support multiple git providers then it’s another story. Let say GitHub and some gitlab instance in the same installation. We will move to this direction but not now.

**Comment by sbryzak** [comment]
Outside scope of auth.
