### ISSUE TITLE
Research Keycloak vacuum strategy regarding expired sessions

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8-services/fabric8-auth#95]
We need to check what KC is doing with expired sessions and is this something we should care in terms of deleting them from DB. We also should research how the token lifespan affects the KC DB size and performance. We should make sure that the long live tokens/sessions won't hit our performance and suck the DB resources.

**Comment by kishansagathiya** [comment]
Only offline tokens require database storage.

Keycloak has regular tokens and offline tokens.  It does not store regular
tokens in memory or on disk.  Instead, we have the concept of a login
session (UserSessionModel) which hold metadata about the login.  These
sessions are stored in memory and within a distributed cache if in a
cluster.  Access and Refresh tokens are minted, digitally signed and
validated and created against metadata within the login session.

Offline tokens are very long lived and thus require their login
session being persisted in a database.
@sbose78

**Comment by kishansagathiya** [comment]
This things are documented here 
http://www.keycloak.org/docs/latest/server_installation/topics/cache.html

**Comment by kishansagathiya** [comment]
Keycloak uses infinispan. Infinispan is a distributed in-memory key/value data store with optional schema.
The data held in these caches is temporary, in memory only, but is possibly replicated across the cluster.
If a server fails, the grid simply creates new copies of the lost data, and puts them on other servers. 
references here https://goo.gl/uRFVcC 
http://www.keycloak.org/docs/3.0/server_installation/topics/cache.html
http://infinispan.org/docs/stable/faqs/faqs.html

**Comment by alexeykazakov** [comment]
We should consider switching infinispan to data grid mode so it will persist sessions in a DB.

**Comment by alexeykazakov** [comment]
Closing. Opened related issue - https://github.com/fabric8-services/fabric8-auth/issues/146
