### ISSUE TITLE
Refresh tokens once a day instead of every 10 minutes

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8-services/fabric8-auth#97]
Currently we refresh tokens every 10 minutes. Originally we did it to pick up possible changes in the list of space collaborators, so, the back-end doesn't have to call Keycloak to check the collaborators every time when user is trying to access some space.
But we don't use RPT tokens anymore and use access tokens only. So, we call Keycloak every time anyway. We don't have to refresh the tokens so often anymore.

We could refresh tokens just once during the day instead.

**Comment by sbryzak** [comment]
Out of scope for auth service.
